feat: backdrop stage abstraction
Tresjs/cientos pull request #116
Opened 2023-07-01 14:29 UTC by alvarosabu

2023-07-03 15:31 UTC, JaimeTorrealba requested changes

2023-07-03 15:31 UTC, JaimeTorrealba commented on public/models/suzanne.json
Why do we add models and textures here in cientos? 

Should not go in assets repo?

2023-07-03 15:31 UTC, JaimeTorrealba commented on docs/public/card-bo-bot/CardBoBot-height.png
Same here, is there a reason why these textures are here? 

Should not go in assets?

2023-07-03 15:44 UTC, JaimeTorrealba commented
I check the example in netlify deploy, but I'm not sure if is right.

https://deploy-preview-116--cientos-tresjs.netlify.app/guide/staging/backdrop.html

![image](https://github.com/Tresjs/cientos/assets/63722373/66e432da-8ef4-4aba-a54b-34c705338412)

2023-07-04 06:53 UTC, alvarosabu commented on public/models/suzanne.json
I though for docs would be ok to have them locally for performance, but seems like that's breaking when statically generating the assets.

2023-07-12 18:26 UTC, merged