draft: first draft of scroll-controls
Tresjs/cientos pull request #118
Opened 2023-07-03 14:35 UTC by JaimeTorrealba

close #63

2023-07-07 15:44 UTC, alvarosabu requested changes
Great work chamo, just some minor things to fix and we can merge this

2023-07-07 15:44 UTC, alvarosabu commented on docs/guide/controls/scroll-controls.md
> +
Can we embed an example here?

2023-07-07 15:44 UTC, alvarosabu commented on src/utils/index.ts
> +export function greaterThanZero(key: string, value: number) {
I will remove this from utils, utils should be plain typescript functions without side effects or use of composables (useLogger).

The name is also miss-leading, `greaterThanZero` implies a boolean (Is this parameter `greaterThanZero` ?) when the function actually logs a warning. 

See my comment on ScrollControls

2023-07-07 15:44 UTC, alvarosabu commented on src/core/controls/ScrollControls.vue
> +greaterThanZero('pages', props.pages)
```suggestion
if(props.smoothScroll < 0) logWarning('SmoothControl must be greater than zero')
if(props.pages < 0) logWarning('Pages must be greater than zero')
```

2023-07-07 15:44 UTC, alvarosabu commented on src/core/controls/ScrollControls.vue
> +  value => {
Add a Type to value

2023-07-07 15:44 UTC, alvarosabu commented on src/core/controls/ScrollControls.vue
> +    initCameraPos = props.horizontal ? value.position.x || 0 : value.position.y || 0
![Screenshot 2023-07-07 at 17 37 18](https://github.com/Tresjs/cientos/assets/4699008/e7f1ba9f-0ac8-49ca-a45d-363b13db36cb)

Try `value?.position.x` and `value?.position.y`

2023-07-07 15:44 UTC, alvarosabu commented on src/core/controls/ScrollControls.vue
> +  }
```suggestion
if (state.camera?.position) {
    const delta =
      (progress.value * props.distance - state.camera.position[direction] + initCameraPos) * props.smoothScroll
    state.camera.position[direction] += delta
    if (wrapperRef.value.children.length > 0) {
      wrapperRef.value.position[direction] += delta
    }
  }
```

2023-07-07 18:16 UTC, JaimeTorrealba commented on docs/guide/controls/scroll-controls.md
> +
How do you think is the best way to do it?

Currently, any abstraction in cientos have one examples (I need to create a task to add examples to all of them)

2023-07-07 18:17 UTC, JaimeTorrealba commented on src/core/controls/ScrollControls.vue
> +  value => {
If I try to add the type Camera, the linter throws errors

2023-07-08 08:16 UTC, alvarosabu commented on src/core/controls/ScrollControls.vue
> +  value => {
The linter is throwing errors as well on the pipeline

2023-07-10 14:48 UTC, merged