feat(cientos): added useDracoLoaderDispose to useGLTF
Tresjs/cientos pull request #127
Opened 2023-07-10 16:49 UTC by Sea-DH1

2023-07-13 09:08 UTC, alvarosabu requested changes

2023-07-13 09:08 UTC, alvarosabu commented on src/core/loaders/useGLTF/index.ts
> +export function useDracoLoaderDispose() {
Hi, @Sea-DH1 thanks for opening the issue and providing a solution.

What if we save the user some trouble and dispose the dracoLoader using `onMounted` hook inside of this composable? That way the end user doesn't need todo it manually

2023-07-18 15:24 UTC, Sea-DH1 commented on src/core/loaders/useGLTF/index.ts
> +export function useDracoLoaderDispose() {
The main reason is that a decoder in it needs to be loaded. If it is disposed of, it will be loaded again next time

2023-07-18 15:55 UTC, Sea-DH1 commented on src/core/loaders/useGLTF/index.ts
> +export function useDracoLoaderDispose() {
> 
I forgot, it can be called there when the webglrenderer is destroyed, so that the user does not have to call it manually

2024-01-26 22:50 UTC, JaimeTorrealba commented on src/core/loaders/useGLTF/index.ts
> +export function useDracoLoaderDispose() {
@Sea-DH1 Hi, could you finally solve this issue?

2024-02-04 15:06 UTC, Sea-DH1 commented on src/core/loaders/useGLTF/index.ts
> +export function useDracoLoaderDispose() {
@JaimeTorrealba 
Hi, I have tried but cannot get the context of TresContext so that I cannot dispose when the WebGLRenderer is destroyed.

2024-02-04 15:12 UTC, JaimeTorrealba commented on src/core/loaders/useGLTF/index.ts
> +export function useDracoLoaderDispose() {
Ok, we have this one available https://docs.tresjs.org/api/composables.html#usetrescontext
But that will only work on the component instance, for the composable. We couldn't have the context yet... In that case, I'll say dispose on the life cycle.

2024-02-05 02:03 UTC, Sea-DH1 commented on src/core/loaders/useGLTF/index.ts
> +export function useDracoLoaderDispose() {
If it is processed in the life cycle, it seems that it cannot be automated, right?

2024-02-16 16:53 UTC, JaimeTorrealba commented on src/core/loaders/useGLTF/index.ts
> +export function useDracoLoaderDispose() {
I don't know any method for that, sorry

2024-04-11 10:06 UTC, hawk86104 reviewed
In this way, after obtaining the model, the memory resources of dracoLoader are automatically released

2024-04-11 13:23 UTC, JaimeTorrealba commented
@hawk86104 Would you like open another issue fixing this one? 

I can close this issue

2024-04-16 15:51 UTC, JaimeTorrealba commented
Done with https://github.com/Tresjs/cientos/pull/383

2024-04-16 15:51 UTC, closed without merging