feat: add reflector
Tresjs/cientos pull request #136
Opened 2023-07-17 23:16 UTC by JaimeTorrealba

close #5

2023-07-19 08:57 UTC, alvarosabu requested changes
Hi @JaimeTorrealba excellent job, I love the result.

I think we should add this to abstractions instead of materials because this implementation actually doesn't solve #5, **it's not a Material** but I see it as a handy abstraction from 'three/addons/objects/Reflector' 

The #5 is an actual material, to be used like this:

```
<TresMesh >
      <TresPlaneGeometry />
      <MeshReflectorMaterial blur="[300, 100]" resolution="2048" />
</TresMesh>
```

Another question would be, how are you handling the reactivity of those props?

2023-07-19 08:59 UTC, alvarosabu requested changes

2023-07-19 08:59 UTC, alvarosabu commented on docs/guide/materials/reflector.md
> +```
When you add a new abstraction, try to be consistent with the documentation, the rest of the docs pages have a section called **Props** with a markdown table of the props. Please add it.

## Props

| Prop             | Description                                          | Default       |
| :--------------- | :--------------------------------------------------- | ------------- |
| `speed`          | Floating speed, higher it rocks more 🤘.             | `1`           |
| `rotationFactor` | Factor for Euler rotation.                           | `1`           |
| `floatFactor`    | Factor for Up/down movement.                         | `1`           |
| `range`          | Range of y-axis values the object will float within. | `[-0.1, 0.1]` |

2023-07-19 09:06 UTC, alvarosabu commented
Docs build is broken, can you check the build locally?
 is broken.

2023-07-19 13:08 UTC, JaimeTorrealba commented on docs/guide/materials/reflector.md
> +```
I agree i'll update the docs

2023-07-19 13:10 UTC, JaimeTorrealba commented
@alvarosabu could be related to this doc's problem https://github.com/Tresjs/cientos/issues/137

2023-07-19 13:16 UTC, JaimeTorrealba commented
In relation to the other comment, You're right is not a material, I'll move it, but It solves the exact same problem of the #5.
Are you sure you don't want to close it?? I mean obviously need some changes in the shaders but the effect you can achieve is the same

As the properties are in the args (And because of the way the Reflector class have been built in, I couldn't figure out how to make reactive props) only the color is reactive

2023-07-19 18:53 UTC, alvarosabu commented
For the ticket leave it open, the idea would be to eventually create te reflector material.

For the reactivity I give you a small clue since you can get the reference of the instance, if one of the argument changes (watch) you could potentially dispose it and re initialize it with the new args. 

Give it a though 😉

2023-07-19 20:19 UTC, JaimeTorrealba commented
I tried already but nothing work, nor dispose the material, geometry.

Nothing works, I Guess I am doing something wrong :(

2023-08-17 12:02 UTC, alvarosabu commented
@JaimeTorrealba can you merge latest main and update this PR, it has been around for long

2023-08-21 15:46 UTC, JaimeTorrealba commented
@alvarosabu I already merge main in this one.

Is not ready yet for merging to main, because is not reactive, when you have some time check it please. If you have any doubts, please let me know.

2023-09-26 17:16 UTC, andretchen0 requested changes

2023-09-26 17:17 UTC, andretchen0 requested changes
Looks good. Here are my suggestions.

2023-09-27 18:19 UTC, JaimeTorrealba commented on docs/.vitepress/config.ts
> -          { text: 'MeshGlassMaterial', link: '/guide/materials/glass-material' },
I probably screw up at some points with the merge, thanks for letting me know this is very important

2023-09-27 18:20 UTC, JaimeTorrealba commented on docs/guide/abstractions/reflector.md
> +| Prop              | Description                                          | Default                   |
I remove the icons, and let just the warning message, the icons seems to be a little too much

2023-09-27 18:20 UTC, JaimeTorrealba commented on docs/guide/abstractions/reflector.md
> +The `cientos` package provides an abstraction of the Reflector class, which creates a reflector material in real time of your scene `<Reflector >` component that makes a geometry as an argument to cr
Nice suggestion

2023-09-27 20:28 UTC, andretchen0 approved these changes
Looks good to me!

2023-11-14 10:56 UTC, alvarosabu requested changes
Hey @JaimeTorrealba awesome to see this updated, can you add a demo to the documentation, this one is especially visual, it would be nice.

2023-11-14 18:17 UTC, merged