feat: 107 use video texture
Tresjs/cientos pull request #167
Opened 2023-08-11 14:22 UTC by JaimeTorrealba

closes #107

2023-08-13 10:06 UTC, alvarosabu requested changes
Looks amazing man, really nice work, just add the error handling to the loading of the video, and we  can merge

2023-08-13 10:06 UTC, alvarosabu commented on src/core/loaders/useVideoTexture.ts
> +        loop,
@JaimeTorrealba please add error handling to the Promise, in case the src is wrong or could not be loaded

2023-08-15 14:20 UTC, JaimeTorrealba commented on src/core/loaders/useVideoTexture.ts
> +        loop,
Done Alvaro

2023-08-17 11:58 UTC, alvarosabu approved these changes

2023-08-17 12:02 UTC, alvarosabu requested changes

2023-08-21 15:35 UTC, JaimeTorrealba commented on src/core/loaders/useVideoTexture.ts
> +      video.addEventListener('error', () => rej())
The error object is pretty much useless, so I'll keep the error log message

![image](https://github.com/Tresjs/cientos/assets/63722373/a27ec747-47fb-4019-9175-5d9ca61e5dba)

2023-08-21 16:46 UTC, alvarosabu requested changes

2023-08-21 16:46 UTC, alvarosabu commented on src/core/loaders/useVideoTexture.ts
> +    return new Promise((res, rej) => {
@JaimeTorrealba please use `resolve` and `reject`. Avoid shorting variable and method names

2023-08-21 17:00 UTC, alvarosabu approved these changes

2023-08-21 17:01 UTC, merged