feat: 23 html component
Tresjs/cientos pull request #184
Opened 2023-08-25 16:12 UTC by alvarosabu

Closes #23

2023-09-19 14:00 UTC, JaimeTorrealba requested changes

2023-09-19 14:00 UTC, JaimeTorrealba commented on docs/.vitepress/config.ts
> +        isCustomElement: (tag: string) => tag.startsWith('Tres') && !whitelist.includes(tag) || tag === 'primitive',
Interesting the templateCompilerOptions are giving problems??

2023-09-19 14:00 UTC, JaimeTorrealba commented on src/core/staging/Sky.vue
> +    :material-uniforms-mie-coefficient-value="props.mieCoefficient"
This will break the sky component, (maybe the pipeline for the lint are not updated here)

2023-09-19 14:00 UTC, JaimeTorrealba commented on src/core/misc/HTML.vue
> +  geometry: new PlaneGeometry(),
Should we add geometry and materials in the docs too?

2023-09-19 14:00 UTC, JaimeTorrealba commented on src/core/misc/HTML.vue
> +const shaders = computed(() => ({
This is a very big component, what do you think if we divide in files?? We could extract many function in a different file and create a structure like
misc/
   HTML/
       index.vue
       defaultVertex.glsl
       defaultFragment.glsl
       utils.ts (here we put function like: getCameraCSSMatrix , isObjectVisible, objectScale ...)

2023-09-19 14:00 UTC, JaimeTorrealba commented on src/core/misc/HTML.vue
> +              if (!Array.isArray(attrs.scale)) {
There are like 6 nested if here :( 
I love the final result, but will be really time-consuming to try to debug this even for you, imagine for someone else.
Besides, inside the loop we're creating too many variables and too many conditionals
Would you like to extract some logic in functions?
Something like,

applyScale(meshRef, attrs.scale) I know will not solve the issue of variables and conditional inside the loop but will be easier to read

2023-09-19 14:21 UTC, alvarosabu commented on src/core/staging/Sky.vue
> +    :material-uniforms-mie-coefficient-value="props.mieCoefficient"
I updated the linter, dunno why it auto-fix it

2023-09-19 14:21 UTC, alvarosabu commented on docs/.vitepress/config.ts
> +        isCustomElement: (tag: string) => tag.startsWith('Tres') && !whitelist.includes(tag) || tag === 'primitive',
yep, in vitepress, is complaining about `primitive` all the time

2023-09-25 12:23 UTC, JaimeTorrealba approved these changes
Please fix that little details and if you want let's not merge until the 3.4 is out.

Meanwhile, I will review the environment

2023-09-25 12:23 UTC, JaimeTorrealba commented on docs/guide/misc/html-component.md
> +
You haven't added the material, and the geometry props, don't forget it please

2023-09-27 06:10 UTC, merged