Feat/lensflare
Tresjs/cientos pull request #185
Opened 2023-08-25 22:38 UTC by andretchen0

@JaimeTorrealba 

Here's the Lensflare as it stands, for discussion. 

## Playground

If you start the playground, the lensflare demo is at http://localhost:5173/abstractions/lensflare

If you refresh the demo, the large "star" in the middle gets a new seed, so it'll look slightly different.

## Lensflare

`src/code/abstractions/Lensflare.vue` could shed about 200 LOC if we dropped the seedable pseudorandom generation. About 150 LOC is setting up then selecting the seeded pseudorandom defaults.

But those 200 lines make it a lot easier for the user to add a Lensflare.

[As mentioned here](https://github.com/Tresjs/cientos/issues/171), a user can currently do this

```
<Lensflare :seed="1918384" />
```

and it'll produce a Lensflare with about 25 elements based on the seed – always the same for the same seed.

This

```
<Lensflare :seed="1918384" :flare="[{texture:'https://myfakeurl.com/images/texture.png'}]" />
```

will replace the seeded first element's texture with the image at the passed url.

If we remove the pseudorandom generation, the user will have to do something like:

```
 <Lensflare :flare="[{ texture: circleBlurTexture, size: 366, distance: 0, color: 'white' },
  { texture: circleTexture, size: 155, distance: -0.3, color: 'gray' },
  { texture: starTexture, size: 512, distance: 0, color: 'gray' },
  { texture: lineTexture, size: 512, distance: 0, color: 'white' },
  { texture: ringTexture, size: 512, distance: 0, color: 'white' },
  { texture: circleTexture, size: 256, distance: 0.6, color: 'gray' },
  { texture: circleTexture, size: 80, distance: 0.7, color: 'gray' },
  { texture: circleBlurTexture, size: 70, distance: 0.9, color: 'white' },
  { texture: circleTexture, size: 65, distance: 1, color: 'white' },
  { texture: circleBlurTexture, size: 60, distance: 1.8, color: 'white' },
  { texture: circleTexture, size: 60, distance: 2.0, color: 'gray' },
  { texture: circleTexture, size: 155, distance: 2.3, color: 'gray' }]" />
```

### Note

The THREE Lensflare isn't really meant to be updated. It makes its elements private. 

I've made the elements reactive to prop changes by hanging on to their references, but updating them is a rather slow process. User input has to be merged with seeded defaults or a default element, then that has to be merged with the THREE Lensflare's elements.

It may be slow if done every frame. Since that's not the way the THREE implementation appears to be meant to work, I didn't worry about it.

----

## RandUtils

For `src/utils/RandUtils`, I reused the parts of THREE's `MathUtils`, but made them use the seedable pseudorandom generator. If a module uses `RandUtils` and always calls methods the same way, it'll always produce the same numbers, array samples, etc. I *think* that could be pretty handy for a project like Cientos, but I don't want to force it on anyone. FWIW, I got the idea from Apple Motion, which takes random seeds for a lot of its objects.

2023-08-29 19:13 UTC, JaimeTorrealba requested changes
First let me tell you thanks for this amazing contributions, I believe almost all the changes are just minimal stuff

Seems really cool, the effect

Even so, in addition to the requested changes:

All the props should be reactive, 
I was trying to changes the seeds from 0 to 10000, but I can't see any visual changes
Have you tried adding your own textures¿? 
We could consider clean a little to the component and extract some logic into other files, what do you think?
The final result could be something like:
abstractions/
     LensFlare/
          index.vue
          Utils (or any other name) // And here put some logic so we 



Sorry for the time to response is a big component, but I'm excited to add this to Cientos 

Also, I'm on the official TresJs Discord for a more quick respond

2023-08-29 19:13 UTC, JaimeTorrealba commented on src/core/abstractions/Lensflare.vue
> +  color: new THREE.Color("white")
We can't pass the color as a prop?

2023-08-29 19:57 UTC, andretchen0 commented
> First let me tell you thanks for this amazing contributions, I believe almost all the changes are just minimal stuff
> 
> Seems really cool, the effect
> 
> Even so, in addition to the requested changes:
> 
> All the props should be reactive, I was trying to changes the seeds from 0 to 10000, but I can't see any visual changes Have you tried adding your own textures¿? We could consider clean a little to the component and extract some logic into other files, what do you think? The final result could be something like: abstractions/ LensFlare/ index.vue Utils (or any other name) // And here put some logic so we
> 
> Sorry for the time to response is a big component, but I'm excited to add this to Cientos
> 
> Also, I'm on the official TresJs Discord for a more quick respond

Thanks for the feedback. I'll go through it and make the changes.

2023-08-31 21:37 UTC, andretchen0 commented on src/core/abstractions/Lensflare.vue
> +    seed: undefined,
> seeds is ok to be undefined here?

The way I've currently defined it, an `undefined` seed has a different meaning than `0`.

Below ...

* `hasSeed` means the seed has a number value
* `hasFlare` means the user has passed flare options.

In the following case, it works like you suggest – no seed was provided, but it defaults to 0:

| hasSeed | hasFlare | Effect |
| --------- | --- | --- |
| `false` | `false` | Use seeded elements with seed == 0 |

But here's the exception, where an `undefined` seed is meaningful:

| hasSeed | hasFlare | Effect |
| --------- | --- | --- |
| `false` | `true` | Use user flare, fill missing values with defaults |

This is the use case I had in mind: 

The user wants to try to create a particular lensflare. 

They don't pass a seed, because they want to create something specific, not random. But they don't want to have to provide all of the options for each `FlareElementProps`, if they like the single `defaultElement`.

I thought defaulting to a single `defaultElement` in this case would make things more predictable for the user.

----

I should say that I'm not attached to things being this way. It's just what made sense to me while writing the code.

I'll follow your lead here.

2023-09-02 02:13 UTC, andretchen0 commented on src/core/abstractions/Lensflare.vue
> +const TEXTURE_PATH = 'https://raw.githubusercontent.com/andretchen0/tresjs_assets/' +
Sure thing. I might need to change some images so I'll keep this in my fork for now. But once it's ready for review, I'll submit a PR to the assets repo.

2023-09-02 02:33 UTC, andretchen0 commented on src/core/abstractions/Lensflare.vue
> +  color: new THREE.Color("white")
Are we talking about a 'global' color prop set on the whole flare to color all the elements? Like so?

```
<TresPointLight :color="new Color(1, 1, 1)" :position="[10, 5, 0]">
  <Lensflare :color="new Color(0, 0, 1)" />
</TresPointLight>
```

## If so, please confirm:

I assume that if a 'global' color prop is set by the user, it ...

* would override the colors of the seeded random values 
* would be overridden by the user provided `flare` array options, e.g.,:

```
<TresPointLight :color="new Color(1, 1, 1)" :position="[10, 5, 0]">
  <Lensflare :color="new Color('blue')" :flare="[{color:'white'}, {color:'yellow', size:64}, {size:124}]" />
</TresPointLight>
```

would have three flare elements: a white, a yellow, and a blue.

2023-09-02 17:08 UTC, andretchen0 commented
@JaimeTorrealba 

I've made most of the requested changes above. Let me know about the remaining issues and we'll move forward.

You can check out the playground at:

http://localhost:5173/abstractions/lensflare

Fwiw, I had earlier included `RandUtils` in `src/utils`, but I don't want to be presumptive about its use. I've moved it into the new `src/core/abstractions/Lensflare` folder.

2023-09-04 14:35 UTC, JaimeTorrealba requested changes
I like the re-organization of the files, we're close to finish this :)

2023-09-04 14:35 UTC, JaimeTorrealba commented on src/core/abstractions/Lensflare/easing.ts
> +}
I found this really useful, but as you say in other conversation

I would move this to utils, other abstraction, could use them

2023-09-04 14:35 UTC, JaimeTorrealba commented on src/core/abstractions/Lensflare/RandUtils.ts
> +}
I would let RandUtils inside the Lensflare folder

2023-09-04 14:35 UTC, JaimeTorrealba commented on src/core/abstractions/Lensflare/index.ts
> +  const oversizeTexturesOptional = [line, ring]
We could give the possibility to the final user to tweak this values, adding them as a prop, in an object format
for example:
const oversize = {
    colors: ["white"]
    ...
}

And so on, and then provide props, so the use could achieve and understand this

I would like to reduce as much as possible hardcode params. Also, if you feel comfortable you can create a constant.ts inside the folder.

2023-09-04 14:38 UTC, JaimeTorrealba commented on src/core/abstractions/Lensflare.vue
> +  color: new THREE.Color("white")
You're right could be a mess, let's keep what you have here

2023-09-04 14:40 UTC, JaimeTorrealba commented on src/core/abstractions/Lensflare.vue
> +    seed: undefined,
In that case, we should provide good docs which explain this case, I found a little hard if the user doesn't know how lensflare works

2023-09-04 19:22 UTC, andretchen0 commented on src/core/abstractions/Lensflare/index.ts
> +  const oversizeTexturesOptional = [line, ring]
> I would like to reduce as much as possible hardcode params.

Sounds good.

I think it'd be really powerful to hand the random presets over to the user. In between other things, I've been poking around with it for a few days, but I find the TS typing is a bit tricky and ends up being unintuitive.

For now, I'll follow your suggestion to put the values in a `constant.ts` file and push. If another module requires the random seeded tools, maybe it can be revisited at that point.

2023-09-06 01:36 UTC, andretchen0 commented
I think I've covered what was discussed. Please let me know if I've misunderstood or forgotten anything.

----

@JaimeTorrealba , you said ...

> We could give the possibility to the final user to tweak this values, adding them as a prop, in an object format
for example:

````
const oversize = {
colors: ["white"]
...
}
````

That's possible now. The seeded props is just an array of entries like this:

````
export const oversize: SeedProps = {
  texture: [line, ring],
  color: ['white'],
  distance: [0, 0],
  size: [750, 1024],
  length: [0, 2],
}
````

There's no longer different logic for generating e.g., "oversize" vs. "front" elements. There's just the different entries in `SeedProps[]`. Hopefully, that makes things cleaner and easier to understand.

----

I incorporated a Leches GUI in the demo with many of the random seeded props – though not all as there are too many of them to fit on my screen.

2023-09-06 08:08 UTC, alvarosabu commented
> I incorporated a Leches GUI in the demo with many of the random seeded props – though not all as there are too many of them to fit on my screen.

@andretchen0 You can create collapsable folders, I forgot to add it to the docs

```ts
const { value } = useControls('folderName', { 
   control1: { value: 1, min:0, max:2, step:0.1 }
})
 ```

2023-09-06 08:11 UTC, alvarosabu commented
@JaimeTorrealba Since I added @andretchen0 to the repo, maybe it will be easy if he creates a branch `feat/171-lensflare` on this repo instead of the fork and just copy all his changes there so we can download it and test it locally

wdyt?

2023-09-06 13:03 UTC, JaimeTorrealba commented
@alvarosabu haha, knew you'd enjoy seeing Leches being used :)

Regarding stopping using the fork or creating a new branch directly in the repo, I would say it depends 100% on @andretchen0, It will definitely be easier to test, but we're almost finished here. We just need the docs and the asset links as far I can tell

2023-09-10 03:31 UTC, andretchen0 commented on src/core/abstractions/Lensflare.vue
> +  color: new THREE.Color("white")
Just FYI, I think this is a good idea, so I've added it.

In addition to the previous props, the user can now also specify any of the props on here:

```
<Lensflare color="blue" :distance="1" :size="512" :texture="[... some path]" />
```

I'll push tomorrow, so you can have a look.

2023-09-10 23:52 UTC, andretchen0 commented
@JaimeTorrealba

## New props: color, distance, size, texture

As mentioned, the user can now put these props directly on the component: color, distance, size, texture.

They serve as defaults. 

* Properties present in user-specified `:elements` will overwrite the defaults.
* The defaults overwrite properties on seeded random elements.

It's handy in a case like this:

```
// Generate some seeded random element and make them all red.
<Lensflare color="red" :seed="99999" />
```

Or:

```
// User sets defaults and then only specifies what differs, using :elements
<Lensflare color="gray" :distance="0" :size="128" :texture="circle" :elements="[
    {color: "white", size: 512},
    {color: "white", texture: rays, size: 256},
    {distance: 0.1},
    {distance: 0.14},
    {distance: 0.16},
    {distance: 0.175},
]" />
```

### Confusion? 

#### Please let me know what you think here. 👈

One potentially confusing case is this:

```
<Lensflare color="red" :distance="0" :size="256" texture="http://..." :seed="99999" />
```

The user has specified a seed, which would normally trigger seeded random element generation. BUT, I ignore it. That's because by specifying all these `{color, distance, size, texture}`, all fields on the seeded random elements would be overwritten.

So, I chose to ignore the seed and just show a **single element** specified by  `{color, distance, size, texture}`.

### Less confusing alternative?

The alternative would be to use the ~20 randomly generated elements, but overwrite all the fields. That leads to a stack of ~20 of the same elements on screen.

----

Feedback is appreciated.

Let me know if this is too confusing.

2023-09-12 15:50 UTC, andretchen0 commented
@JaimeTorrealba 

I've added the docs at http://localhost:5173/guide/abstractions/lensflare.html

Still waiting on https://github.com/Tresjs/assets/pull/7 but once that's done and the texture paths are updated here, this is ready to go, unless there are more requested changes.

2023-09-12 17:19 UTC, JaimeTorrealba commented
@andretchen0 perfect, I already approved the https://github.com/Tresjs/assets/pull/7
So I'll make some last test and we're ready to go :)

2023-09-12 22:32 UTC, andretchen0 commented
I've updated the paths to point at Tres Assets. 

The Tresjs/assets readme says:

> Repository containting static assets for TresJS demos on [Stackblitz](https://stackblitz.com/@alvarosabu/collections/tresjs)

I use those assets as defaults for the Lensflare. That means they will likely be used in Cientos' users' software. Is that ok, or should they be placed somewhere else?

2023-09-13 15:58 UTC, JaimeTorrealba commented
I have to say, incredible work!!! It's a huge contribution

When you feel ready, please remove the draft-status and let's merge it 

Also, if you want, the demo component for lensFlare will be really useful in the [Playground](https://github.com/Tresjs/playground) let me know if you would like to add it there (after finalizing this PR of course)

2023-09-13 15:58 UTC, andretchen0 commented
> BTW all the images you have used are free of charge right?

Yes. I made them using GIMP and the canvas API.

They are free to use and unencumbered by licenses.

2023-09-13 17:30 UTC, JaimeTorrealba approved these changes

2023-09-13 17:30 UTC, merged

2023-09-13 23:21 UTC, andretchen0 commented
> Also, if you want, the demo component for lensFlare will be really useful in the [Playground](https://github.com/Tresjs/playground) let me know if you would like to add it there (after finalizing this PR of course)

Sure, that would be great.

Would you like me to fork the playground repo?

2023-09-13 23:24 UTC, JaimeTorrealba commented
Yes, but you're now part of the Tres org right?
Now you don't need to fork, just download the repo :)

2023-09-13 23:41 UTC, andretchen0 commented
Oh, sorry. I had to fork tres-assets because I wasn't part of that team.

Ok. I'll just create a branch then. Thanks!