feat: 177 add more examples into the docs
Tresjs/cientos pull request #202
Opened 2023-09-06 15:23 UTC by JaimeTorrealba

closes #177 

This is ready, but first this one https://github.com/Tresjs/cientos/pull/198 should be merged

2023-09-12 11:58 UTC, alvarosabu requested changes
All of them work but the Precipitation one https://deploy-preview-202--cientos-tresjs.netlify.app/guide/staging/precipitation.html take a look @JaimeTorrealba

2023-09-12 12:24 UTC, JaimeTorrealba commented
[Precipitation _ Cientos.webm](https://github.com/Tresjs/cientos/assets/63722373/a1ea8831-179e-4fa5-951a-1bff9cfd0e68)
I don't see problems @alvarosabu 
What's the issue??

2023-09-12 12:27 UTC, alvarosabu commented
<img width="1407" alt="Screenshot 2023-09-12 at 14 27 02" src="https://github.com/Tresjs/cientos/assets/4699008/825d9b38-a35e-4afb-b085-9744aa58d00a">

2023-09-12 17:47 UTC, alvarosabu approved these changes

2023-09-13 12:00 UTC, alvarosabu commented
If you give me the ok @JaimeTorrealba we can merge

2023-09-13 12:40 UTC, JaimeTorrealba commented on docs/.vitepress/theme/components/ScrollControlsDemo.vue
> +      html-scroll
I will change this first @alvarosabu

2023-09-13 13:31 UTC, merged