feat(Sky): add Sky
Tresjs/cientos pull request #213
Opened 2023-09-15 01:22 UTC by andretchen0

#106 

If this looks ok, I'll add the docs.

----

## Question: Template kebab case `lint --fix` problem

Is there a workaround for this?

`pnpm run lint --fix` throws an error and "fixes" the kebab case on the last line:

```
  <primitive
    :object="skyImpl"
    :material-uniforms-mieCoefficient-value="props.mieCoefficient"
```

transforming it into this

```
  <primitive
    :object="skyImpl"
    :material-uniforms-mie-coefficient-value="props.mieCoefficient"
```

but the "fix" causes an error to be thrown in the browser, when run.

I solved the problem by using `watch`, but if there's a way around it, I'd love to know.

Thanks!

2023-09-15 12:47 UTC, alvarosabu commented
Hi @andretchen0 thanks for this, regarding the lint, yes, a similar thing happens with `shadow.mapSize.width` here in the lint config https://github.com/Tresjs/configs/blob/v0.2.0/packages/eslint-config-vue/index.js#L137-L139

Please add a PR on the repo with the exception(s) you need

2023-09-15 14:48 UTC, andretchen0 commented
Thanks, @alvarosabu . Will do.

> Please add a PR on the repo with the exception(s) you need

Do you prefer focused, case-by-case exceptions? 

`'material-uniforms-mieCoefficient-value', 'material-uniforms-mieDirectionalG-value', 'material-uniforms-sunPosition-value'`

But setting uniforms is common in `Three`, so maybe a more general approach is useful? Maybe ...

`-uniforms-`

[Looking at the linter source](https://github.com/vuejs/eslint-plugin-vue/blob/791a60d7234da16fe86dddcdc7c2744bd5c3415e/lib/rules/attribute-hyphenation.js#L120C7-L120C7), it appears that the general approach would work, but it's [not explicitly documented at the moment](https://eslint.vuejs.org/rules/attribute-hyphenation.html).

2023-09-15 15:13 UTC, alvarosabu commented
Mmm, I see, with uniforms is not scalable 🤔

2023-09-15 23:27 UTC, andretchen0 commented
Opened a [PR for the linter hyphenation fix.](https://github.com/Tresjs/configs/pull/3)

2023-09-16 15:08 UTC, JaimeTorrealba requested changes
Excellent work, I just have little details, when you fix them I'll approve them but no merge this until the https://github.com/Tresjs/configs/pull/3 it's finished

2023-09-16 15:08 UTC, JaimeTorrealba commented on docs/guide/staging/sky.md
> +| `turbidity`         | Haziness                                                                                                                            | `3.4`   |
Here you forgot the distance prop

2023-09-16 15:08 UTC, JaimeTorrealba commented on playground/src/pages/staging/SkyDemo.vue
> +  exposure: { value: 0.5, min: 0, max: 1, step: 0.01 },
Same here, the distance Props :)

2023-09-16 15:08 UTC, JaimeTorrealba commented on playground/src/pages/staging/SkyDemo.vue
> +const skyRef = shallowRef(null)
Here this is empty because, it's necessary to add the defineExpose

2023-09-16 15:08 UTC, JaimeTorrealba commented on playground/src/pages/staging/SkyDemo.vue
> +    <OrbitControls :zoom-speed="0" />
We could use here disable-pan (and if you want disabled zoom too)

2023-09-16 21:12 UTC, andretchen0 commented on playground/src/pages/staging/SkyDemo.vue
> +const skyRef = shallowRef(null)
I removed the ref.

2023-09-16 21:13 UTC, andretchen0 commented on playground/src/pages/staging/SkyDemo.vue
> +  exposure: { value: 0.5, min: 0, max: 1, step: 0.01 },
Added

2023-09-16 21:13 UTC, andretchen0 commented on docs/guide/staging/sky.md
> +| `turbidity`         | Haziness                                                                                                                            | `3.4`   |
Added

2023-09-16 21:13 UTC, andretchen0 commented on playground/src/pages/staging/SkyDemo.vue
> +    <OrbitControls :zoom-speed="0" />
Done

2023-09-16 21:32 UTC, andretchen0 commented
@JaimeTorrealba 

> I just have little details

All good stuff. Thanks for the feedback.

> when you fix them I'll approve them but no merge this until the [Tresjs/configs#3](https://github.com/Tresjs/configs/pull/3) it's finished

[The config changes were merged](https://github.com/Tresjs/configs/pull/3) – though it seems like the [CI linter here on Github](https://github.com/Tresjs/cientos/pull/213/commits/a62b6d2fd7d4050c1218fd63e0986f961ea8ed3a#diff-bcb1b58e8e953711ce44278df539b7606cdffdceb65be40747ab67c97e79672e) hasn't been updated. 

I think Sky is ready to merge. Otherwise, let me know what changes need to be made and I'll update the component.

2023-09-16 23:40 UTC, JaimeTorrealba approved these changes
Thanks for this
We really appreciate it

2023-09-17 13:29 UTC, JaimeTorrealba commented
@alvarosabu This is ready, but I don't want to merge it until the linter pipeline get update.
Please let me know about this

2023-09-17 18:05 UTC, alvarosabu commented
@JaimeTorrealba I released a new version of the linter, you guys should be able to add it

2023-09-17 19:26 UTC, merged