feat(cientos): 178 v-light-helper
Tresjs/cientos pull request #214
Opened 2023-09-15 18:07 UTC by JaimeTorrealba

This will not close the issue 178

2023-09-16 10:03 UTC, alvarosabu requested changes

2023-09-16 10:03 UTC, alvarosabu commented on src/core/directives/vLightHelper.ts
> +    const currentHelper = helpers[el.type]
Looks good, add a unmounted to dispose the helper as well

2023-09-16 15:05 UTC, alvarosabu requested changes

2023-09-16 15:05 UTC, alvarosabu commented on src/core/directives/vLightHelper.ts
> +    el.parent.remove(currentInstance)
@JaimeTorrealba  The helper would not be free from memory unless you call `.dispose()` 
![Screenshot 2023-09-16 at 17 04 44](https://github.com/Tresjs/cientos/assets/4699008/1277ad63-5790-4177-808f-6e3ba97d0842)

https://threejs.org/docs/#manual/en/introduction/How-to-dispose-of-objects

2023-09-16 15:10 UTC, JaimeTorrealba commented on src/core/directives/vLightHelper.ts
> +    el.parent.remove(currentInstance)
Good eye there, thanks, I forgot to dispose it.

Fix is on his way :)

2023-09-16 15:37 UTC, alvarosabu approved these changes

2023-09-16 15:38 UTC, alvarosabu requested changes

2023-09-16 15:38 UTC, alvarosabu commented on docs/guide/directives/v-light-helper.md
> +Note that you can pass a modifier with the name of a property, for example `v-log:material`, and will log directly the `material` property
Copy paste ;) @JaimeTorrealba

2023-09-16 16:01 UTC, alvarosabu commented
@JaimeTorrealba dunno if it's possible but add an update call `helper.update()` everytime there is a change in the light. Otherwise the helped will remind in the same place if you move the light or change the color

2023-09-17 13:21 UTC, JaimeTorrealba commented
Interesting, I could use it with the renderLoop, or in the update directive cycle

1. With the renderloop is the same as the request animation frame, will not be performance problems right?
2. Option 2 it will only trigger when a reactive property (Vue) of the element changes (which is not always the case)

2023-09-18 14:38 UTC, alvarosabu commented
> Interesting, I could use it with the renderLoop, or in the update directive cycle
> 
> 1. With the renderloop is the same as the request animation frame, will not be performance problems right?
> 2. Option 2 it will only trigger when a reactive property (Vue) of the element changes (which is not always the case)

I will go for the second option since the update is not like the `controls.update()` which needs to be inside of the renderLoop

2023-09-18 15:52 UTC, alvarosabu approved these changes

2023-09-18 15:53 UTC, merged