feat: 178 v distance to
Tresjs/cientos pull request #220
Opened 2023-09-19 16:16 UTC by JaimeTorrealba

closes #178

2023-10-05 18:08 UTC, JaimeTorrealba commented
@andretchen0 I know if a lot to see, but if you find time, without rush please check this too

2023-10-05 22:45 UTC, andretchen0 requested changes
Works as advertised. 👍

There a couple language changes to make in the docs. Nothing major.

Otherwise, I made some suggestions:

* Based on the comments in the code, you were looking for a way to incorporate other displays. I made a suggestion for the API, but feel free to implement or not.
* Currently, passing a null ref to `v-distance-to` throws an unhandled error. Personally, I'd prefer to have a guard there to do some type checking, then `console.warn` if the ref isn't an object with a position. But it's your call.

2023-10-05 22:45 UTC, andretchen0 commented on src/core/directives/vDistanceTo.ts
> +    // TODO see other way to show the distance
Keeping the console as the default doesn't bug me here – I'm guessing `v-distance-to` is mainly a debugging tool, used by people who know how things are logged to the console.

For other ideas, [you might have a look here](https://vuejs.org/guide/reusability/custom-directives.html#hook-arguments) for how to pass extra args.

E.g. StatsGL uses a 'mode' field. If we want to stick with that, then maybe something like ...:

```
// Default: log to console
<Sphere v-distance-to="otherSphereRef">
```

```
// Display in a custom StatsGL window
<Sphere v-distance-to:mode.statsgl="otherSphereRef">
```

2023-10-05 22:45 UTC, andretchen0 commented on playground/src/pages/directives/vDistanceTo.vue
> +import { TresCanvas, useRenderLoop } from '@tresjs/core'
`useRenderLoop` is unused, so it can be removed.

2023-10-05 22:45 UTC, andretchen0 commented on src/core/directives/vDistanceTo.ts
> +    const observer = extractBindingPosition(binding)
Currently, if you pass an empty ref to `v-distance-to` it throws an error, stopping the app.

Maybe it would be useful to fail silently or `console.warn` here if the passed ref doesn't point to an object with a position.

I tried switching between two objects with a single ref. This works as expected:

```
<script setup lang="ts">
import { shallowRef } from 'vue'
import { TresCanvas, useRenderLoop } from '@tresjs/core'
import { OrbitControls, Sphere, vDistanceTo } from '@tresjs/cientos'
import { SRGBColorSpace, NoToneMapping, Vector3 } from 'three'
import { useControls, TresLeches } from '@tresjs/leches'
import '@tresjs/leches/styles'

const gl = {
  clearColor: '#333',
  outputColorSpace: SRGBColorSpace,
  toneMapping: NoToneMapping,
}

const sphere1Ref = shallowRef()
const sphere2Ref = shallowRef()
const distToRef = shallowRef({clone:() => new Vector3(0,0,0), position:new Vector3(0,0,0)})

const { value: slider } = useControls({
  slider: {
    value: -2,
    min: -4,
    max: 2,
    step: 0.1,
  },
})

useRenderLoop().onLoop(({elapsed}) => {
  if (Math.sin(elapsed) > 0) {
    distToRef.value = sphere1Ref.value
  } else {
    distToRef.value = sphere2Ref.value
  }
})
</script>

<template>
  <TresLeches class="top-0 important-left-4" />
  <TresCanvas v-bind="gl">
    <TresPerspectiveCamera :position="[0, 2, 5]" />
    <Sphere
      ref="sphere1Ref"
      :position="[-2, slider, 0]"
      :scale="0.5"
    />
    <Sphere
      ref="sphere2Ref"
      :position="[5, slider, 0]"
      :scale="0.5"
    />
    <Sphere
      v-distance-to="distToRef"
      :position="[2, 0, 0]"
      :scale="0.5"
    />
    <TresGridHelper :args="[10, 10]" />
    <OrbitControls />
  </TresCanvas>
</template>
```

So maybe it would be handy if this ...

```
const distToRef = shallowRef({clone:() => new Vector3(0,0,0), position:new Vector3(0,0,0)})
```

... could just be this momentarily, without causing an error ...

```
const distToRef = shallowRef()
```

2023-10-06 12:48 UTC, JaimeTorrealba commented on docs/guide/directives/v-distance-to.md
> +¿Have you tried to calculate the distance between two object with ThreeJs?
This is because I'm Spanish speaker hahaha

2023-10-06 13:48 UTC, JaimeTorrealba commented on src/core/directives/vDistanceTo.ts
> +    // TODO see other way to show the distance
For now, I'll just let the consoles, if the people use this directive, and it's necessary in the future we could improve this one

2023-10-06 13:49 UTC, JaimeTorrealba commented on src/core/directives/vDistanceTo.ts
> +    const observer = extractBindingPosition(binding)
I handle the error with a simple validation and logging the warm, This was also the case for the vAlwaysLookAt directive. Thanks for detect this

2023-10-06 14:44 UTC, andretchen0 requested changes
Looks good!

Just one more thing! 🤪

2023-10-06 14:44 UTC, andretchen0 commented on src/core/directives/vDistanceTo.ts
> +    const observer = extractBindingPosition(binding)
Great! That keeps the app from stopping.

Can I make a further suggestion?

Can you add some info to the logged message? Maybe ...

``
logWarning(`v-distance-to: ${binding} is not a "Object3D"`)
``

## Context

Here's what `useLogger` currently outputs:

<img width="882" alt="Screenshot 2023-10-06 at 16 30 18" src="https://github.com/Tresjs/cientos/assets/20469369/0b83079c-0771-4dc1-a0ef-4040731f0772">

* Unlike with a thrown `Error`, when `console.log`ging, you don't get a call stack. You just get the file/line number of the `console.log`. 
* And the file/line number reported by `useLogger` is `useLogger`'s own line number, not `v-distance-to`'s.

That means you don't get context for the problem, making it hard to find.

2023-10-06 20:08 UTC, JaimeTorrealba commented
If I was better with Typescript I could definitely do something better, but for now I'll validate manually :D

I appreciate this feedbacks

2023-10-06 20:09 UTC, JaimeTorrealba commented
@andretchen0 I'll be on vacations from 14 - oct, to 04 nov

So I'll not make more PRs for now, please take care of cientos 🙏

2023-10-06 21:53 UTC, andretchen0 approved these changes
Looks good!

2023-10-06 21:59 UTC, andretchen0 commented
> @andretchen0 I'll be on vacations from 14 - oct, to 04 nov

Sounds good. See you in november!

2023-10-07 14:08 UTC, alvarosabu commented
@andretchen0 Hey there! Thanks for taking care of reviewing, what do you think, ready to merge?

2023-10-07 14:16 UTC, alvarosabu approved these changes
Looks pretty handy @JaimeTorrealba

2023-10-07 14:35 UTC, andretchen0 commented
> @andretchen0 Hey there! Thanks for taking care of reviewing, what do you think, ready to merge?

It's ready to go, I believe.

2023-10-07 14:38 UTC, merged