docs: fix minor typos, phrasing, outdated props
Tresjs/cientos pull request #223
Opened 2023-09-20 12:50 UTC by andretchen0

I've updated some of the docs here. Mostly correcting minor typos and adjusting some phrasing. 

The PR also updates [outdated props names/defaults in the table here.](https://cientos.tresjs.org/guide/abstractions/mouse-parallax.html#props)

----

Let me know if this sort of fix is welcome. If so, I'll keep going. If not, then I'll stop. No problem either way.

----

I'm not an editor. My only relevant qualification is being an anglophone. 🤪

2023-09-20 13:48 UTC, JaimeTorrealba requested changes
Thank you for this, I re-read some texts and find some little improvements

2023-09-20 13:48 UTC, JaimeTorrealba commented on docs/guide/misc/stats.md
> +[stats.js](https://github.com/mrdoob/stats.js/) is a JavaScript performance monitor, made by [mrdoob](https://github.com/mrdoob). stats.js provides a simple info box that will help you monitor your c
This mistake ... hahaha

2023-09-20 13:48 UTC, JaimeTorrealba commented on docs/guide/abstractions/mouse-parallax.md
> +You only need import it and add it to your template as `<MouseParallax />`. Additionally, you can pass the following props.
to import

the following props:

2023-09-20 14:54 UTC, JaimeTorrealba commented
Of course, these types of fix are welcome and appreciated :)

Are you in discord? Or is there any more direct way to contact to you @andretchen0?

2023-09-20 15:39 UTC, andretchen0 commented
> Are you in discord? 

I'm not on Discord very often; I just joined the server. I have to be a member for at least 10 minutes to send a message. ;)

2023-09-20 16:07 UTC, andretchen0 commented on docs/guide/misc/stats.md
> +[stats.js](https://github.com/mrdoob/stats.js/) is a JavaScript performance monitor, made by [mrdoob](https://github.com/mrdoob). stats.js provides a simple info box that will help you monitor your c
Lol. Yeah. This whole PR was really just to fix that.

2023-09-22 16:22 UTC, andretchen0 commented
Hey @JaimeTorrealba I made the wording changes you pointed out above.

Following the quick exchange on Discord, I added a "Usage" header where it was missing. In a few places, that meant reordering things a bit.

Since I was looking at usage examples, I also reformatted a lot of them – mostly cosmetic stuff. Especially:

* changing the "language" of the example – e.g., `html` -> `vue`
* changing the highlighted lines so that the relevant lines are emphasized

2023-09-22 16:22 UTC, andretchen0 commented on docs/guide/abstractions/mouse-parallax.md
> +You only need import it and add it to your template as `<MouseParallax />`. Additionally, you can pass the following props.
Done

2023-09-22 17:33 UTC, JaimeTorrealba commented on docs/guide/controls/keyboard-controls.md
> +```vue{5}
Why Vue 5 here?? (I'm not good with markdown)

2023-09-22 20:51 UTC, andretchen0 commented on docs/guide/controls/keyboard-controls.md
> +```vue{5}
> Why Vue 5 here?? (I'm not good with markdown)

No problem. It took me some searching to find the docs for the extensions.

That extension is for [syntax and line highlighting.](https://vitepress.dev/guide/markdown#line-highlighting-in-code-blocks) 

Using the extension, this:

```
```vue{5}
```

... means:

* Begin codeblock. 
* Use Vue syntax highlighting. 
* Highlight line 5.

2023-09-24 12:52 UTC, andretchen0 commented
@JaimeTorrealba 

Merging is blocked for me, but I can't find any more requested changes. Can you review and merge if everything is ok? Thanks!

2023-09-24 15:15 UTC, JaimeTorrealba approved these changes

2023-09-24 15:15 UTC, merged