Add `useFBO()` abstraction
Tresjs/cientos pull request #228
Opened 2023-09-21 19:36 UTC by kekkorider

Closes #149

2023-09-21 20:58 UTC, JaimeTorrealba commented
Since useTresContextProvider() is a provide/inject value, I believe you can't use outside setup context

Maybe we can convert this one into a renderlessComponent
You can base on the [StatsGL](https://github.com/Tresjs/cientos/blob/main/src/core/misc/StatsGl.ts) component, for example.

2023-09-21 21:04 UTC, JaimeTorrealba requested changes
Look good  :)

2023-09-21 21:04 UTC, JaimeTorrealba commented on src/core/staging/Sky.vue
> +    :material-uniforms-mie-coefficient-value="props.mieCoefficient"
This will break this abstraction @alvarosabu, what is needed here to use the linter propertly? a git pull??

2023-09-21 21:04 UTC, JaimeTorrealba commented on src/core/abstractions/useFBO.ts
> +  const _width = typeof width === 'number' ? width : size.width * viewport.dpr
We could pass default values in the props or in the parameters, 
but these types of validations  (for type) are not necessary, for that is typescript :)

2023-09-21 21:19 UTC, kekkorider commented on src/core/abstractions/useFBO.ts
> +  width?: number | FBOSettings,
That comes from Drei.

IMHO this is in case you do not specify the size (i.e. fullscreen) and you provide the settings object as first parameter.

2023-09-21 21:21 UTC, kekkorider commented on src/core/staging/Sky.vue
> +    :material-uniforms-mie-coefficient-value="props.mieCoefficient"
Don't blame me, I simply ran `pnpm lint --fix` 😄

2023-09-21 21:22 UTC, kekkorider commented on src/core/abstractions/useFBO.ts
> +  const _width = typeof width === 'number' ? width : size.width * viewport.dpr
Yeah I was thinking the same thing, but I was having a lot of errors in the editor (despite everything was working).
So I copypasted this stuff as-is from Drei.

2023-09-21 21:24 UTC, JaimeTorrealba commented on src/core/abstractions/useFBO.ts
> +  const _width = typeof width === 'number' ? width : size.width * viewport.dpr
Let's make it works and then we see if we can clean something :)

2023-09-21 21:25 UTC, JaimeTorrealba commented on src/core/staging/Sky.vue
> +    :material-uniforms-mie-coefficient-value="props.mieCoefficient"
I know heheh this was an issue in others PRs too

2023-09-21 23:23 UTC, kekkorider commented
Now we have something 🥸


https://github.com/Tresjs/cientos/assets/5191941/e0d6b4fe-d3db-4d1b-9b01-d300ca8aecfb

2023-09-22 08:43 UTC, alvarosabu commented on src/core/staging/Sky.vue
> +    :material-uniforms-mie-coefficient-value="props.mieCoefficient"
@kekkorider please merge last main with the eslint over-rule and set the tmeplate of this file to:

```
  <primitive
    :object="skyImpl"
    :material-uniforms-turbidity-value="props.turbidity"
    :material-uniforms-rayleigh-value="props.rayleigh"
    :material-uniforms-mieCoefficient-value="props.mieCoefficient"
    :material-uniforms-mieDirectionalG-value="props.mieDirectionalG"
    :material-uniforms-sunPosition-value="sunPosition"
    :scale="props.distance"
  />
```

2023-09-22 08:53 UTC, kekkorider commented on src/core/staging/Sky.vue
> +    :material-uniforms-mie-coefficient-value="props.mieCoefficient"
@alvarosabu I just rebased and force-pushed (I'm used to work this way instead merging `main`).
After running `pnpm lint --fix` everything was ok as expected.

2023-09-22 08:56 UTC, alvarosabu requested changes
Excellent first contribution @kekkorider 👏🏻

Just change the naming convention to `Fbo` rather than `useFbo` since is not composable and change the file from a `ts` to a `vue` component to ensure better reactivity

2023-09-22 08:56 UTC, alvarosabu commented on src/core/abstractions/useFBO.ts
> +export const UseFBO = defineComponent<UseFboProps>({
Since this is a component rather than a composable I would probably avoid using `use` prefix and turn this file into a SFC vue component called `<Fbo />` rather than a `ts` component.

This will make things easier for the props.

Also is not reactive, if any of the props change the target is not disposed and created again.

@kekkorider take a look at this component https://github.com/Tresjs/cientos/blob/main/src/core/staging/ContactShadows.vue  let me know if you need help.

2023-09-22 12:47 UTC, JaimeTorrealba commented on playground/src/pages/abstractions/FBODemo.vue
> +        :map="fboRef?.texture || null"
Question, this way of using is good, but it feels a little odd...

Since it is useful to use a renderless component, could this be made with slots?

Something like:

<FBO>
   <TresMeshBasicMaterial />
</FBO>

Is that possible, did you find comfortable? The FBO is use only in :map property? 
What do you think, guys?

2023-09-23 09:05 UTC, alvarosabu commented on playground/src/pages/abstractions/FBODemo.vue
> +        :map="fboRef?.texture || null"
@JaimeTorrealba how would it look if done via slots for example?

2023-09-23 13:26 UTC, JaimeTorrealba commented on playground/src/pages/abstractions/FBODemo.vue
> +        :map="fboRef?.texture || null"
In the code could be something like:

const slots = useSlots()
const material = slot.default()[0].children.material // and here you access the material of the slot component
//and you can assign the "texture" created directly, obviously some validations are needed first

Just by the record, I'm not demanding a change, you did this abstraction @alvarosabu you know what is better, is just I feel this way of usage a little weird, you don't. Other solutions are considered too

2023-09-26 09:04 UTC, kekkorider commented
I refactored everything to make it a renderless component following the new naming convention as @alvarosabu requested.

Basically it works, but whenever I change a prop the box turns black (no map set).
I'm logging the UUID of the FBO texture in the browser console and it stays the same no matter what.

2023-09-27 12:58 UTC, JaimeTorrealba reviewed
@alvarosabu when you have time please check this one, when the components have WebGlRenders I couldn't make then reactive... Example of that is the Reflector, so please if you know a way to achieve this, comment us

2023-09-28 14:50 UTC, kekkorider commented
@alvarosabu awesome! I will work on it next week. 🍻

2023-10-05 12:49 UTC, kekkorider commented
@alvarosabu @JaimeTorrealba I guess we're there 🥳

2023-10-06 04:45 UTC, alvarosabu commented
Hey @kekkorider amazing job! There seem to be some conflicts with `main`, could you please check it?

2023-10-06 13:04 UTC, kekkorider commented
> Hey @kekkorider amazing job! There seem to be some conflicts with `main`, could you please check it?

@alvarosabu I just rebased and removed the conflicts 🙌

2023-10-06 14:03 UTC, JaimeTorrealba requested changes
Great work man, the component looks nice, I'll include it for the next v3.5 of cientos 
Thanks you 
 I've just some little changes, docs related, and one question

2023-10-06 14:03 UTC, JaimeTorrealba commented on docs/components.d.ts
> +    FboDemo: typeof import('./.vitepress/theme/components/FboDemo.vue')['default']
Also, please remove the components.d.ts 
Sometimes create conflicts (This is my fault, I need to handle this probably with a git ignore or something)

2023-10-06 14:14 UTC, kekkorider commented on docs/guide/abstractions/fbo.md
> +	await nextTick()
This basically ensures that the `refs` are not null when referencing them in the code 🙌

2023-10-06 14:15 UTC, kekkorider commented on docs/components.d.ts
> +    FboDemo: typeof import('./.vitepress/theme/components/FboDemo.vue')['default']
You mean removing the file entirely or just that line?

2023-10-06 14:15 UTC, JaimeTorrealba commented on docs/guide/abstractions/fbo.md
> +	await nextTick()
Oohh good one I didn't know about this :) Thanks

2023-10-06 15:07 UTC, kekkorider commented on docs/guide/abstractions/fbo.md
> +# FBO <Badge type="warning" text="^3.5.0" />
Done!

2023-10-06 16:51 UTC, kekkorider commented on docs/guide/abstractions/fbo.md
> +```ts
I wasn't aware of this feature, it'a really cool 🤩

Done!

2023-10-06 16:53 UTC, kekkorider commented
@JaimeTorrealba I just fixed everything you asked 🙌

2023-10-06 18:26 UTC, JaimeTorrealba approved these changes
It has been a difficult one :D. But great work. 

I'll not merge until @alvarosabu check this one but see everything fine

2023-10-06 18:27 UTC, JaimeTorrealba commented on docs/guide/abstractions/use-fbo.md
> +The `useFBO` composable must be used inside of a child component since it needs the context of TresCanvas.
@alvarosabu quick question here: this is not solved with the 
https://github.com/Tresjs/tres/pull/404??? it's necessary this warning?

2023-10-07 14:05 UTC, alvarosabu approved these changes
Brilliant work @kekkorider @JaimeTorrealba

2023-10-07 14:05 UTC, alvarosabu commented on docs/guide/abstractions/use-fbo.md
> +The `useFBO` composable must be used inside of a child component since it needs the context of TresCanvas.
No, one thing is that you can get the context via templateRef and the other is that the context provider is not going to work on the setup of the parent component.

2023-10-07 14:07 UTC, merged