feat: change stats renderless component
Tresjs/cientos pull request #243
Opened 2023-10-04 17:56 UTC by JaimeTorrealba

2023-10-04 22:19 UTC, andretchen0 requested changes
Looks good!

It seems like everything is working well. ;) 

I made some suggestions for changes to wording, links, etc.

2023-10-04 22:19 UTC, andretchen0 commented on docs/guide/misc/stats.md
>  - CUSTOM User-defined panel support.
Maybe link to the [custom panel example](https://github.com/mrdoob/stats.js/blob/master/examples/custom.html) in the original repo here?

Or maybe provide a demo?

(I'm not sure how much time you want to spend here. Just a suggestion.)

2023-10-05 17:51 UTC, JaimeTorrealba commented on docs/guide/misc/stats.md
>  - CUSTOM User-defined panel support.
I have never created a custom panel, so I'll just put the link to the repo here

2023-10-05 23:14 UTC, andretchen0 requested changes
There's just one change and then it's ready to go.

2023-10-05 23:14 UTC, andretchen0 commented on docs/guide/misc/stats.md
> +- 3+: CUSTOM User-defined panel support, for mor info please check [stats.js](https://github.com/mrdoob/stats.js/).
> 3+: CUSTOM User-defined panel support, for mor info please check ...

3+: CUSTOM User-defined panel support. For more info please check ...

* 'support. For' – the other entries have periods, so just for consistency 
* 'mor' -> 'more'

2023-10-06 12:47 UTC, JaimeTorrealba commented on docs/guide/misc/stats.md
> +- 3+: CUSTOM User-defined panel support, for mor info please check [stats.js](https://github.com/mrdoob/stats.js/).
Thanks for this

2023-10-06 13:55 UTC, andretchen0 approved these changes
👍

2023-10-06 14:00 UTC, merged