feat: 170 use gltf exporter
Tresjs/cientos pull request #290
Opened 2023-11-25 21:52 UTC by JaimeTorrealba

closes #170

2023-11-27 19:00 UTC, alvarosabu requested changes

2023-11-28 10:01 UTC, JaimeTorrealba commented on src/core/misc/useGLTFExporter.ts
> +  return true
In this case not, this is a side effect function doesn't return anything. I removed the return statement

2023-11-28 14:31 UTC, alvarosabu requested changes
Sorry chamo, can't pass this with an `any`, isn't the type `TresObject3D` helpful here?

2023-11-28 14:31 UTC, alvarosabu commented on src/core/misc/useGLTFExporter.ts
> +    ( gltf: any ) => {
Sorry chamo, can't pass this with an `any`, isn't the type TresObject3D helpful here?

2023-12-05 11:07 UTC, andretchen0 reviewed
Nice job! Works as expected. For me, there are just a few points to look over.

2023-12-15 14:04 UTC, alvarosabu commented
Hey @andretchen0 could you check if all the conversations where solved please?

2023-12-15 14:42 UTC, andretchen0 commented
> Hey @andretchen0 could you check if all the conversations where solved please?

Will do.

2023-12-15 19:12 UTC, andretchen0 commented
Hey @JaimeTorrealba

It looks like these are still pending:

* https://github.com/Tresjs/cientos/pull/290/files#r1415365368
* https://github.com/Tresjs/cientos/pull/290/files#r1415366462
* https://github.com/Tresjs/cientos/pull/290/files#r1415373969

😉

2023-12-18 16:55 UTC, JaimeTorrealba commented
@andretchen0 sorry I haven't paid attention to this notification. Sorry.

Done :). And thanks, as you may guest I'm not good with the English grammar

2023-12-18 19:26 UTC, andretchen0 commented
> @andretchen0 sorry I haven't paid attention to this notification. Sorry.
> 
> Done :). And thanks, as you may guest I'm not good with the English grammar

No worries man. You're doing a lot better than me in my second language, lol.

2023-12-18 20:41 UTC, andretchen0 approved these changes
Looks good to me!

2023-12-19 08:27 UTC, alvarosabu commented
Awesome, @JaimeTorrealba merge latest main to resolve conflicts and we are ready to merge this PR

2023-12-25 22:57 UTC, JaimeTorrealba commented
@alvarosabu  done :D

2024-01-08 13:01 UTC, andretchen0 requested changes
Since merging in main, the playground example is broken. It'll need to be converted to Leches.

2024-01-08 13:01 UTC, andretchen0 commented on playground/src/pages/misc/GLTFExporterDemo.vue
> +const { pane } = useTweakPane()
Since there's no `useTweakPane` this should probably be converted to `Leches`.

2024-01-09 13:23 UTC, JaimeTorrealba commented on playground/src/pages/misc/GLTFExporterDemo.vue
> +const { pane } = useTweakPane()
You're complete right, thanks for pointing Andre. It's already fix

2024-01-12 18:04 UTC, andretchen0 requested changes
Nice job. Works as advertised! Just one small typo to fix.

I'll approve the PR either way, but as an optional addition, could we also show how to download the whole Tres scene? No problem if you'd rather keep it simple.

2024-01-15 10:57 UTC, andretchen0 approved these changes
Great! Thanks for adding the scene example.

2024-01-15 11:34 UTC, JaimeTorrealba commented
@alvarosabu please your approval here is necessary :)

2024-01-26 13:47 UTC, JaimeTorrealba commented
@alvarosabu sorry for tag you again, I would like to merge this one :)

2024-01-29 10:04 UTC, alvarosabu approved these changes

2024-01-29 10:05 UTC, merged