feat: add BakeShadows component
Tresjs/cientos pull request #324
Opened 2023-12-25 22:25 UTC by JaimeTorrealba

closes #321  
How can I remove these warnings

![image](https://github.com/Tresjs/cientos/assets/63722373/f2ca2831-1b2d-4bf5-a5fe-dab2cac6cc0e)

2023-12-26 10:10 UTC, alvarosabu commented on src/core/misc/BakeShadows.ts
@JaimeTorrealba probably because you are defining any props

2023-12-26 11:40 UTC, JaimeTorrealba commented on src/core/misc/BakeShadows.ts
But <Stats /> has props, and the messages still appears

2023-12-31 22:42 UTC, andretchen0 commented
About the color error, the `color` prop on `TresMeshStandardMaterial` expects a `THREE.Color`, so any of [the instantiation examples here](https://threejs.org/docs/#api/en/math/Color) will work, like this:

```
<TresMeshStandardMaterial :color="new Color(0x00ff00)" />
```

2024-01-01 00:36 UTC, andretchen0 requested changes

2024-01-01 00:36 UTC, andretchen0 commented on src/core/misc/BakeShadows.ts
> +    return null
Remove `return null`. I believe this fixes the typing issue. Let me know if that doesn't fix it for you.

[Fwiw, here's an example with no returned value in the Vue docs.](https://vuejs.org/guide/typescript/composition-api.html#without-script-setup)

2024-01-01 00:36 UTC, andretchen0 commented on playground/src/pages/misc/BakeShadows.vue
> +      <TresMeshStandardMaterial :color="0x00ff00" />
`TresMeshStandardMaterial`'s `color` prop expects a `THREE.Color`, so you'll have to instantiate one with `new Color(...)`.

2024-01-01 00:36 UTC, andretchen0 commented on playground/src/pages/misc/BakeShadows.vue
> +      <TresMeshStandardMaterial :color="0xf7f7f7" />
Same as above. This should be a `THREE.Color`, not a number.

2024-01-09 13:31 UTC, JaimeTorrealba commented on src/core/misc/BakeShadows.ts
> +    return null
Thank you so much, it was that 🙏

2024-01-09 13:31 UTC, JaimeTorrealba commented on playground/src/pages/misc/BakeShadows.vue
> +      <TresMeshStandardMaterial :color="0xf7f7f7" />
Same here

2024-01-09 13:31 UTC, JaimeTorrealba commented on playground/src/pages/misc/BakeShadows.vue
> +      <TresMeshStandardMaterial :color="0x00ff00" />
Done :)

2024-01-09 17:30 UTC, andretchen0 approved these changes
Looks good to me!

2024-01-09 17:43 UTC, merged