feat(app): Add shadow camera helpers to v-light-helper
Tresjs/cientos pull request #337
Opened 2024-01-26 19:01 UTC by JaimeTorrealba

2024-01-27 15:37 UTC, andretchen0 requested changes
Hey @JaimeTorrealba !

I've found some bugs and made a few suggestions for getting rid of them.

There are also a few changes/suggestions for typos, etc.

😎

2024-01-27 15:37 UTC, andretchen0 commented on src/core/directives/vLightHelper.ts
> +  el.parent.children.find((child: any) => child instanceof CameraHelper)
I think this approach is causing some problems. If you `el.parent.children.find` there might be multiple instances of a particular `instanceof`, if there are sibling lights.

## Suggestion

LightHelpers and CameraHelpers store a reference to their targets. You could match on those.

2024-01-27 15:37 UTC, andretchen0 commented on src/core/directives/vLightHelper.ts
> +let currentShadowCameraHelper: any
I think these variables are out of sync when the code reaches line 29. Iirc:

* Create SpotLight 1, add helper
* Create PointLight 2, add helper
* updated() on Light 1 <-- `getHelperInstance` will return the PointLight helper instance

## Suggestion

If you want to store references, maybe something like this?

```
type LightHelper = DirectionalLightHelper | PointLightHelper | SpotLightHelper | HemisphereLightHelper | RectAreaLightHelper
const lightUuidToShadowCameraHelper: Record<string, CameraHelper> = {}
const lightUuidToLightHelper: Record<string, LightHelper> = {}
```

2024-01-29 10:19 UTC, JaimeTorrealba commented
@andretchen0 thanks for taking the time, I like your feedback. I'm going to put this in draw because we're moving the directive section to the core pkg. So I don't know yet what will happen with this one

2024-02-09 16:51 UTC, JaimeTorrealba commented
I'll close this one, since now the directives are in the core (I'll re-open there)

2024-02-09 16:51 UTC, closed without merging