feat: rounded box
Tresjs/cientos pull request #348
Opened 2024-02-08 16:04 UTC by JaimeTorrealba

2024-02-08 16:07 UTC, alvarosabu commented
Hi @JaimeTorrealba this is planned for v4 or would be better to have it available on an ealier version?

2024-02-08 16:09 UTC, JaimeTorrealba commented
I would say not for the v4. @alvarosabu

2024-02-09 14:50 UTC, andretchen0 requested changes
Hey @JaimeTorrealba ,

Looks good! Just some minor changes/cleanup.

2024-02-09 14:50 UTC, andretchen0 commented on playground/src/pages/shapes/RoundedBoxDemo.vue
> +<script setup>
Missing `lang="ts"`

2024-02-09 14:50 UTC, andretchen0 commented on docs/guide/shapes/rounded-box.md
> +# Rounded-box <Badge type="warning" text="^3.8.1" />
Probably best to use the component name as the page title:

```
# RoundedBox <Badge type="warning" text="^3.8.1" />
```

2024-02-09 14:50 UTC, andretchen0 commented on docs/.vitepress/theme/components/RoundedBoxDemo.vue
> +  <TresLeches class="top-0 important-left-4" />
There's no Leches instance, so this can be removed.

2024-02-09 14:50 UTC, andretchen0 commented on playground/src/components/TemplatePage.vue
What's this component? (Maybe it was added to the commit by mistake?)

2024-02-09 14:50 UTC, andretchen0 commented on docs/.vitepress/theme/components/RoundedBoxDemo.vue
> +import { shallowRef, watch, Fragment } from 'vue'
None of the imports here are used, so this line can be deleted.

2024-02-10 21:55 UTC, andretchen0 commented on docs/guide/shapes/rounded-box.md
> +# Rounded-box
(Non-blocking)

(I see that the badge was removed, but "Rounded-box" wasn't changed. I'm not sure if that was intentional.)

My preference would be to change this to ...

```
# RoundedBox
```

... since that's the name of the component. But there are some kebab-case names in the docs site, so I won't hold up the PR.

2024-02-10 21:56 UTC, andretchen0 approved these changes
Looks good. I approved the PR.

There's one comment to look at, but it's not blocking.

2024-02-11 23:58 UTC, JaimeTorrealba commented on docs/guide/shapes/rounded-box.md
> +# Rounded-box
Nop you're right, I'll fix this.

2024-02-12 10:25 UTC, merged

2024-02-12 15:08 UTC, andretchen0 reviewed
Great!