feat: 252 ocean component
Tresjs/cientos pull request #363
Opened 2024-03-11 16:44 UTC by JaimeTorrealba

closes #252

2024-03-11 17:26 UTC, alvarosabu requested changes
This opens an "Ocean" of opportunities 😂. Sorry, only chance to drop a bad pun

2024-03-11 17:26 UTC, alvarosabu commented on src/core/staging/Ocean.vue
> +const WaterRef = shallowRef()
```suggestion
const waterRef = shallowRef()
```

2024-03-11 17:26 UTC, alvarosabu commented on src/core/staging/Ocean.vue
> +  WaterRef,
I would align this to the decision made on https://github.com/Tresjs/cientos/issues/160#issuecomment-1935873027 to be consistent

2024-03-11 17:26 UTC, alvarosabu commented on src/core/staging/Ocean.vue
> +    WaterRef.value.material.uniforms.sunDirection.value.copy(sunPosition)
```suggestion
    waterRef.value.material.uniforms.sunDirection.value.copy(sunPosition)
```

2024-03-11 17:26 UTC, alvarosabu commented on src/core/staging/Ocean.vue
> +  WaterRef.value.material.uniforms.time.value += delta
```suggestion
  waterRef.value.material.uniforms.time.value += delta
```

2024-03-11 17:26 UTC, alvarosabu commented on src/core/staging/Ocean.vue
> +    ref="WaterRef"
```suggestion
    ref="waterRef"
```

2024-03-11 17:26 UTC, alvarosabu commented on src/core/staging/Sky.vue
> +  value: skyRef,
https://github.com/Tresjs/cientos/issues/160#issuecomment-1935873027 ?

2024-03-11 17:29 UTC, alvarosabu commented
![Screenshot 2024-03-11 at 18 28 30](https://github.com/Tresjs/cientos/assets/4699008/84c8f975-e7d4-40ac-99ce-c2a896796ac7)

Looks amazing! @JaimeTorrealba is sun direction always required?

2024-03-11 17:35 UTC, JaimeTorrealba commented on src/core/staging/Sky.vue
> +  value: skyRef,
Lol I come with the idea and I forget it hahaha sorry I'll fix it :D

2024-03-11 18:02 UTC, andretchen0 commented
Currently reviewing. But just wanted to say that it looks great!

2024-03-11 18:39 UTC, andretchen0 requested changes
Hey @JaimeTorrealba !

Just a few changes. Mostly typos and mostly non-blocking.

Looks great!

2024-03-11 18:39 UTC, andretchen0 commented on docs/guide/staging/ocean.md
> +Smoke componente comes with a default texture abstraction it needs to be wrapped by a Suspense component
> Smoke componente

I think this should be one of 

* The `<Ocean />` component
* The Ocean component
* `<Ocean />`
* Ocean

I guess I prefer `<Ocean />`.
 
(Sometimes we use `<Tag />`. We should probably come up with a "rule" for ourselves.)

Also, maybe add a period at the end of the sentence.

2024-03-11 18:39 UTC, andretchen0 commented on docs/guide/staging/ocean.md
> +| Prop                | Description                                 | Default                                                                                          |
(Non-blocking)

Just in case this component slipped by you: you can use the `CientosPropsTable` like so:

```
<CientosPropsTable component-path="src/core/staging/Ocean.vue" :fields="['name', 'description', 'default']" />
```

That will create a formatted table like the one you've typed, but it'll stay updated with the JSDoc comments in the component's source code. (Unfortunately, it doesn't help with translations, though.)

No worries if you don't want to use it though. Just mark as "resolved".

Though if you have ideas for improving `<CientosPropsTable />`, I'm all ears.

2024-03-11 18:39 UTC, andretchen0 commented on docs/guide/staging/ocean.md
> +The `<Ocean />` work pair to pair with the [Sky](https://cientos.tresjs.org/guide/staging/sky.html) component, detecting the position of the sun and reflecting on the water.
> The `<Ocean />` work pair to pair with the

The `<Ocean />` component works hand in hand with the

2024-03-11 18:39 UTC, andretchen0 commented on docs/guide/staging/ocean.md
> +(`<Sky />` component is not required for making this component work)
> (`<Sky />` component is not required for making this component work)

(`<Sky />` is not required for making this component work.)

2024-03-11 18:39 UTC, andretchen0 commented on docs/guide/staging/ocean.md
> +The `<Ocean />` component also react when there's [Fog](https://threejs.org/docs/index.html?q=fog#api/en/scenes/Fog) or [FogExp2](https://threejs.org/docs/index.html?q=fog#api/en/scenes/FogExp2) on y
> react

reacts

> on your scene.

in your scene.

2024-03-11 18:39 UTC, andretchen0 commented on docs/guide/staging/ocean.md
> +You can usw a custom geometry by simple adding as a slot
> You can usw a custom geometry by simple adding as a slot

Maybe:

You can use custom geometry by adding it as a child.

## Rationale for "adding it as a child"

It seems to me that you, @JaimeTorrealba , as the creator of the component, added the `<slot />`.

That enables the user of the component to add a child.

2024-03-11 18:39 UTC, andretchen0 commented on playground/src/pages/staging/OceanDemo.vue
> +const newSunDirection = new Vector3(10, 0, 0)
(Non-blocking)

This could be removed since it isn't referenced anywhere.

2024-03-11 18:39 UTC, andretchen0 commented on playground/src/pages/staging/OceanDemo.vue
> +import { shallowRef, watch } from 'vue'
(Non-blocking)

This could be removed since the imports aren't used.

2024-03-12 16:56 UTC, JaimeTorrealba commented on docs/guide/staging/ocean.md
> +| Prop                | Description                                 | Default                                                                                          |
I couldn't make it works, Andre. I don't know what happen (I have a new computer) the cientosPropsTable is just not working for me even after build the repo.

I got.

![image](https://github.com/Tresjs/cientos/assets/63722373/65d205a6-2df2-4e34-a0f2-73d52fef5233)

So I just use the manual approach, any idea what it could be?

2024-03-12 17:03 UTC, andretchen0 requested changes
I think my earlier comments about a few language changes weren't clear.

Below, I've put the entire sentences to copy/paste.

✌️

2024-03-13 15:12 UTC, andretchen0 approved these changes

2024-03-13 15:38 UTC, alvarosabu approved these changes
🌊

2024-03-13 15:40 UTC, merged