feat: 246 positional audio
Tresjs/cientos pull request #365
Opened 2024-03-14 12:08 UTC by damienmontastier

## Issue [#246](https://github.com/Tresjs/cientos/issues/246) (Positional Audio)

[Local Playground](http://localhost:5173/abstractions/positional-audio) — `pnpm run playground`

[Local Documentation](http://localhost:5173/) — `pnpm run docs:dev` ***(in progress)***
___

@alvarosabu, @JaimeTorrealba 

This is my first PR on Cientos and I wanted to get your feedback so that I can improve the code/operation as much as possible in line with user expectations. 🤙

___

### Description
Component based on the Three.js [Positional Audio](https://threejs.org/docs/index.html?q=posi#api/en/audio/PositionalAudio) class. It includes a helper that makes it easier to visualise the sound emission. This helper is based on [PositionalAudioHelper](https://threejs.org/docs/#examples/en/helpers/PositionalAudioHelper).

### Feedbacks

- I couldn't use the `extend({})` principle for `<PositionalAudioHelper>`, because it depends on `<TresPositionalAudio>` which is itself asynchronous, maybe I wasn't being logical, do you have any ideas?
- The defineExpose doesn't work? I wanted to export a `ref()` and `console.log` this value in the parent (in my case the PositionalAudio page of the playground). But it's not possible, I end up with undefined. Currently, to access the elements I have to : 
```vue
<script setup lang="ts">
  const positionalAudioRef = shallowRef(null);

  watch(positionalAudioRef, () => {
    const { exposed } = positionalAudioRef.value.$
    console.log(exposed)
  })
</script>

<template>
    <Suspense>
      <PositionalAudio ref="positionalAudioRef" url="/positional-audio/sound1.mp3" />
    </Suspense>
</template>
```
- Unfortunately [@tresjs/leches](https://tresleches.tresjs.org/) is not available without passing through `<TresLeches>` in the template, which greatly limits its use for example with a helper during development. In the case of this Positional Audio composant, it would be cool if you could set parameters directly via the GUI. Maybe create a single instance of `<TresLeches>` and then add elements inside it? Maybe there's a way out of this, if you need help with that or want to contribute to [@tresjs/leches](https://tresleches.tresjs.org/) I can help! I even have ideas for news Controls to develop. 👀
- One last point which I don't think depends on Tres, but rather directly on Three.js. The [PositionalAudioHelper](https://threejs.org/docs/#examples/en/helpers/PositionalAudioHelper) class seems to offer 2 materials: materialInnerAngle, materialOuterAngle (with two different colors by default: `0x00ff00` & `0xffff00`. [Source Code](https://github.com/mrdoob/three.js/blob/master/examples/jsm/helpers/PositionalAudioHelper.js). But I don't see any lines in yellow, am I crazy? hahaha 😂

### Todo

- Writing documentation

2024-03-15 13:29 UTC, damienmontastier reviewed
I've added this part to counter a problem with the three.js package. I'm going to open an issue, but in the meantime I've fixed it with this part of the code 🤙

2024-03-15 14:49 UTC, JaimeTorrealba commented
Hi @damienmontastier no problem, I wouldn't use extend for this one, it is more an abstraction. Similar to <globalAudio />

- Is still defineExpose not working for you? Please let me know (I check your code, and it seems ok) it should work we have all our component working with it
- Leches is under heavy development, and we the core team agree to re-think it. But as in every pkg any help is highly appreciated

- When I saved it, my code gets automatically linter. No idea what config do you have to do sorry (we will ask Alvaro later)
- I've never run at the same time :). But could handle to do it

Is this component ready to review I've seen many new commits coming into???

2024-03-15 15:52 UTC, andretchen0 commented
@damienmontastier 

> About pnpm lint: is there an efficient way to ensure that the lint modifies the code each time it is saved ? (on VSCode)

Fwiw, for the time being, you could set up your own [git hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) to run the linter. (At least for me, `pnpm run lint --fix` is relatively slow and I wouldn't want it to run every time I saved.)

Coincidentally, [I just opened a similar issue on Tres for this.](https://github.com/Tresjs/tres/issues/590) It's a proposal to run the linter before git pushes files to Github and halt pushes that include linter errors. (With an opt-out.)

2024-03-15 16:13 UTC, damienmontastier commented
Hey @JaimeTorrealba ! 

- Strange, I tried again and `defineExpose` works... I'm going to adapt my code!

No, it's not ready for review yet, I need to add an example and correct my lint errors.

———

@andretchen0 !

It could indeed be interesting! When I see 100 `lint` errors to correct by hand, I get scared haha... after all, we're all a bit lazy! 😆 

——

I also noticed another potential problem: when I use my core component `<PositionalAudio>` in the doc, the `onUnmounted` is never called in this file, so I had to add a `dispose()` function to the `defineExpose()` and call it in the parent... Do you have any solutions?

2024-03-15 16:25 UTC, JaimeTorrealba commented
@damienmontastier. Please let me know when this is ready :)

- Regarding the dipose() that could be another issue. Many components use the onUnmouted to dispose their instance, I'll check it later
- You could add a close word in the description of this PR to link it to the issue [more info](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests)  
- Also, you could put this PR in "draft"mode so we know when is ready (optional)

:)

2024-03-15 17:16 UTC, andretchen0 commented
> When I see 100 lint errors to correct by hand, I get scared haha

Maybe you know, but just in case it's helpful: 

The linter can fix many common errors if you do `pnpm run lint --fix`.

Just make sure all your open files are saved. That will save you 'overwrite' warnings in the editor.

2024-03-15 23:33 UTC, damienmontastier commented
> > When I see 100 lint errors to correct by hand, I get scared haha
> 
> 
> 
> Maybe you know, but just in case it's helpful: 
> 
> 
> 
> The linter can fix many common errors if you do `pnpm run lint --fix`
> 
> 
> 
> Just close or save any open, edited files in the editor before you run the linter. Otherwise, the editor will throw 'overwrite' warnings when you eventually save those files.

Finally, I found a way to lint on code save with the VSCode extension ESLint 🤙 Thanks 👌

2024-03-19 07:45 UTC, damienmontastier commented
Hey! PR over! I've just got a problem and I can't seem to solve it, so if you've got any ideas... On the component documentation there are two demos and there seems to be a sound problem, the sounds seem to crackle... When you comment on one of the two demos everything works perfectly... I can't figure out why...

2024-03-19 17:13 UTC, JaimeTorrealba requested changes
Great work @damienmontastier. I just drop some little reviews, nothing too big.

Sorry for asking you to move the assets, but in cientos we should not have assets (except images). I'll update the contribution guide adding this definition.

2024-03-19 17:13 UTC, JaimeTorrealba commented on docs/public/positional-audio/sound1.mp3
This should be removed from cientos and add it to the assets pkg

2024-03-19 17:13 UTC, JaimeTorrealba commented on playground/public/positional-audio/sound.mp3
Same this

2024-03-19 17:13 UTC, JaimeTorrealba commented on src/core/abstractions/PositionalAudio.vue
> +  ref: positionalAudioRef,
This should be changed for `root`.

More info here: https://github.com/Tresjs/cientos/issues/160. Will be a new standard

2024-03-19 17:13 UTC, JaimeTorrealba commented on docs/guide/abstractions/positional-audio.md
> +| **outerGain**        | `number` —  A parameter for directional audio sources, this is the amount of volume reduction outside of the `outerAngle` prop. When the value is `0` no sound can be heard. |
Will be useful to explain, the methods available. (the one you define in the define expose, and how to access them here in the docs) Also if you like the idea to add some events. (explication below)

2024-03-19 17:13 UTC, JaimeTorrealba commented on src/core/abstractions/PositionalAudio.vue
> +  if (autoplay.value && ready.value) playAudio()
Completely optional, but here could be a good idea to add some reactive methods using emits

like (isPlaying) and/or others parameters useful

2024-03-19 17:16 UTC, JaimeTorrealba requested changes
Great work @damienmontastier. I just drop some little reviews, nothing too big.

Sorry for asking you to move the assets, but in cientos we should not have assets (except images). I'll update the contribution guide adding this definition.

And big thanks for this.

2024-03-19 17:16 UTC, JaimeTorrealba commented on docs/guide/abstractions/positional-audio.md
> +<<< @/.vitepress/theme/components/PositionalAudioDemoHelper.vue{4,15,71,93-105}
I don't know what you think, but for showing the code, I would prefer something short and easy to read (we have a lot of beginners). In this case I would do it manually with the minimal necessary for the positionalAudio component to work

2024-03-23 08:43 UTC, damienmontastier commented on docs/guide/abstractions/positional-audio.md
> +| **distance**        | `number` — The distance at which the volume reduction starts taking effect. ***A non-negative number.***  | `1`                   |
The PannerNode API used by PositionalAudio from Three.js already has an error message when the value is negative, in this case `distance = -2` ([doc](https://developer.mozilla.org/en-US/docs/Web/API/PannerNode/refDistance))

![Capture d’écran 2024-03-23 à 09 40 51](https://github.com/Tresjs/cientos/assets/33467958/55cb03f1-765a-45a6-9884-580e0df48642)

2024-03-23 08:45 UTC, damienmontastier commented on docs/guide/abstractions/positional-audio.md
> +The `cientos` package provides an abstraction of the [PositionalAudio](https://threejs.org/docs/index.html?q=posi#api/en/audio/PositionalAudio), `<PositionalAudio>` is an object specifically designed
This will be modified in the next commit, thank you 👌

2024-03-23 08:46 UTC, damienmontastier commented on docs/guide/abstractions/positional-audio.md
> +This component is still under development, so please report any problems or suggestions on the [@tresjs/cientos](https://github.com/Tresjs/cientos) repository on GitHub.
You're right about the "under development" part, but should I remove the helper part as well?

2024-03-23 08:56 UTC, damienmontastier commented on docs/guide/abstractions/positional-audio.md
> +<img src="/positional-audio/sketch.jpg" />
This will be modified in the next commit, thank you 👌

2024-03-23 09:02 UTC, damienmontastier commented on src/core/abstractions/PositionalAudio.vue
> +  ref: positionalAudioRef,
This will be modified in the next commit, thank you 👌

2024-03-24 14:45 UTC, JaimeTorrealba commented on docs/guide/abstractions/positional-audio.md
> +This component is still under development, so please report any problems or suggestions on the [@tresjs/cientos](https://github.com/Tresjs/cientos) repository on GitHub.
Nop the helper part is good (idk why appears highlighted)

2024-03-24 14:45 UTC, JaimeTorrealba commented on docs/guide/abstractions/positional-audio.md
> +| **distance**        | `number` — The distance at which the volume reduction starts taking effect. ***A non-negative number.***  | `1`                   |
Fantastic :)

2024-03-29 08:34 UTC, damienmontastier commented on playground/public/positional-audio/sound.mp3
I created a PR on the repo assets

2024-03-29 08:34 UTC, damienmontastier commented on docs/public/positional-audio/sound1.mp3
I created a PR on the repo assets

2024-03-29 08:35 UTC, damienmontastier commented on docs/.vitepress/theme/components/PositionalAudioDemo.vue
> +const model = await useGLTF('/positional-audio/pingpong.glb', { draco: true })
I created a PR on the repo assets

2024-03-29 08:37 UTC, damienmontastier commented on docs/guide/abstractions/positional-audio.md
> +<<< @/.vitepress/theme/components/PositionalAudioDemoHelper.vue{4,15,71,93-105}
I agree with you about the length of the "demo" code. It might be interesting to create direct clickable links to the demo source code (on github)

2024-04-29 09:59 UTC, damienmontastier commented
Hey @alvarosabu @JaimeTorrealba ! I've changed quite a few things, it looks like it's a good version, let me know! ✌️

2024-04-29 10:00 UTC, damienmontastier commented on docs/guide/abstractions/positional-audio.md
> +| **outerGain**        | `number` —  A parameter for directional audio sources, this is the amount of volume reduction outside of the `outerAngle` prop. When the value is `0` no sound can be heard. |
I added some elements to the doc in the last commit!

2024-04-29 10:01 UTC, damienmontastier commented on src/core/abstractions/PositionalAudio.vue
> +  if (autoplay.value && ready.value) playAudio()
I added some elements to the doc in the last commit

2024-04-30 12:20 UTC, JaimeTorrealba approved these changes
Great job!!!

2024-04-30 12:20 UTC, merged