feat(app): Add holographic material to cientos
Tresjs/cientos pull request #370
Opened 2024-03-25 15:53 UTC by JaimeTorrealba

2024-03-25 21:06 UTC, andretchen0 commented
@JaimeTorrealba 

Sounds cool! Will review tomorrow.

2024-03-25 23:14 UTC, andretchen0 requested changes
Hey @JaimeTorrealba !

Looks great! Nice addition!

Just a few changes.

2024-03-25 23:14 UTC, andretchen0 commented on docs/guide/materials/holographic-material.md
> +| **enableBlinking**     | Enables or disables the blinking effect.                            | `Boolean`                                           | true      |
This line can be deleted. It was added to the table twice.

2024-03-25 23:14 UTC, andretchen0 commented on docs/guide/materials/holographic-material.md
> +### You can also replace the material of an existing mesh like this:
(non-blocking)

To me, it looks a little funny to have this long header floating between 2 code blocks. Maybe change to:

````
### Replace a mesh's material

You can also replace the material of an existing mesh like this:
````

2024-03-25 23:22 UTC, andretchen0 commented on src/core/materials/holographicMaterial/material.ts
> +// Original author Anderson Mancini - https://github.com/ektogamat/threejs-vanilla-holographic-material
@JaimeTorrealba @alvarosabu 

Is this sufficient for the license? 

I have zero legal knowledge, but reading over [the MIT license from the repo](https://github.com/ektogamat/threejs-vanilla-holographic-material/blob/main/LICENSE), it sounds like the whole text needs to accompany Anderson Mancini's code.

Here's the salient bit:

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

2024-04-05 15:22 UTC, JaimeTorrealba commented
I already implemented all the feedbacks, as always thanks for take your time to do it, and the quality of them, it makes me grow as a professional and have a better library.

Btw the **levioso** advice it was just perfect 👍

2024-04-06 14:20 UTC, andretchen0 approved these changes

2024-04-06 14:24 UTC, andretchen0 commented
> I already implemented all the feedbacks, as always thanks for take your time to do it, and the quality of them, it makes me grow as a professional and have a better library.

That's really nice to hear. Thanks!

2024-04-08 13:33 UTC, merged