feat(app): Add Environment, allowing it to mount sub-components and Lightformer via FBO
Tresjs/cientos pull request #382
Opened 2024-04-11 01:28 UTC by hawk86104

Modified at: https://github.com/Tresjs/cientos/pull/374
Preview: https://hawk86104.github.io/#/plugins/skyBox/newEnvironment 
 && https://hawk86104.github.io/#/plugins/industry4/showLambo
![image](https://github.com/Tresjs/cientos/assets/29882682/389bc724-d09c-44aa-9a14-959b76ea8702)

**modifying the Environment, enabling us to replicate R3F use cases using Vue3**
```vue
<Suspense>
    <Environment :blur="1" background :far="10000">
        <Lightformer :intensity="0.75" :rotation-x="Math.PI / 2" :position="[0, 5, -9]" :scale="[10, 10, 1]" />
        <Lightformer :intensity="4" :rotation-y="Math.PI / 2" :position="[-5, 1, -1]" :scale="[20, 0.1, 1]" />
        <Lightformer :rotation-y="Math.PI / 2" :position="[-5, -1, -1]" :scale="[20, 0.5, 1]" />
        <Lightformer :rotation-y="-Math.PI / 2" :position="[10, 1, 0]" :scale="[20, 11, 1]" />

        <Levioso :speed="5" :floatFactor="2" :rotationFactor="2">
            <Lightformer form="ring" color="red" :intensity="1" :scale="10" :position="[-15, 4, -18]" />
        </Levioso>

        <TresGroup :rotation="[0, 0.5, 0]">
            <TresGroup ref="group">
                <Lightformer v-for="( i, x ) in lightFormerPositions " :key="i" form="circle" :intensity="2"
                    :rotation="[Math.PI / 2, 0, 0]" :position="[x, 4, i * 4]" :scale="[3, 1, 1]" />
            </TresGroup>
        </TresGroup>

        <TresMesh :scale="[100, 100, 100]">
            <TresSphereGeometry :args="[1, 64, 64]" />
            <TresMeshNormalMaterial />
        </TresMesh>
    </Environment>
</Suspense>
```

2024-04-16 14:49 UTC, JaimeTorrealba requested changes
Nice work, thanks for this, I just drop little comments.

But important I don't see the documentation for this one, please remember to add it.

2024-04-16 14:49 UTC, JaimeTorrealba commented on src/core/staging/useEnvironment/lightformer/index.vue
> +      v-if="props.from === 'circle'"
Tip: Props are unnecessary here. You can use just from

2024-04-16 14:49 UTC, JaimeTorrealba commented on src/core/staging/useEnvironment/lightformer/index.vue
> +
I realize many of the code here is from r3f. Please remember to add it in the comments.

2024-04-17 01:28 UTC, hawk86104 commented on src/core/staging/useEnvironment/lightformer/index.vue
> +      v-if="props.from === 'circle'"
thx，ok

2024-04-17 07:53 UTC, hawk86104 commented
Maybe It's already refined

2024-04-18 00:29 UTC, hawk86104 commented on docs/guide/staging/environment.md
> +## Lightformer
1. Making the documentation more detailed is even better. I've further refined it.
2. I also prefer describing something on a single page. After all, LightFormer is a small feature in itself.

2024-04-18 16:23 UTC, JaimeTorrealba approved these changes

2024-04-18 16:23 UTC, merged

2024-04-18 16:24 UTC, JaimeTorrealba commented
@hawk86104 Thanks man :)