fix: camera controls ignored props
Tresjs/cientos pull request #385
Opened 2024-04-18 16:33 UTC by whereiswolf

- Fixes https://github.com/Tresjs/cientos/issues/384
- Adds support for `mouseButtons` and `touches` prop.
- Adds default `mouseButtons` and `touches` prop values based on https://yomotsu.github.io/camera-controls/examples/config.html
- Adds support for partial overrides of `mouseButtons` and `touches`.

---
Feel free to point out at any mistakes and discrepancies from conventions. I have a strong React background, and some aspects of Vue are kinda new to me 😜

2024-04-19 14:44 UTC, JaimeTorrealba requested changes
Hey this work perfect, is very professional, thanks for this one.

But remember to update the docs for the component (adding the new props and maybe and example of the type that you can use, better be really explicit for the final user).

2024-04-19 16:15 UTC, JaimeTorrealba commented
I agree with you, I would do it @whereiswolf (maybe you can export it in the defaultExpose ¿?)

2024-04-21 19:03 UTC, whereiswolf commented
@JaimeTorrealba quick summary of the recent changes:

- Updated `CameraControls` docs with "User input config" section.
- Added logic to check the camera type, to set the default values in the same way as `camera-controls` does.
- Added `CameraControlsClass` re-export of `camera-controls` (if you have a better name suggestion please lmk 😄 )

If anything's unclear or should be changed, I'm happy to work on that 😉

2024-04-22 08:44 UTC, JaimeTorrealba commented on src/core/controls/CameraControls.vue
> +export { default as CameraControlsClass } from 'camera-controls'
Sorry for the late I was off this weekend.

I love the result. The only thing I am not sure is the name "CameraControlsClass" could that create confusion for some users? (since ThreeJs is basically made in classes) 

But I don't have a better name, maybe CameraControlsPointers?

2024-04-22 10:15 UTC, whereiswolf commented on src/core/controls/CameraControls.vue
> +export { default as CameraControlsClass } from 'camera-controls'
Yeah, I wasn't sure about that either, what about `ThreeCameraControls` or `BaseCameraControls`? Maybe I miss something, but `Pointers` adds more ambiguity in my opinion 😛.

As one said:
> There are only two hard things in Computer Science: cache invalidation and naming things.

2024-04-22 10:18 UTC, JaimeTorrealba commented on src/core/controls/CameraControls.vue
> +export { default as CameraControlsClass } from 'camera-controls'
I like BaseCameraControls :)

2024-04-22 10:42 UTC, whereiswolf commented on src/core/controls/CameraControls.vue
> +export { default as CameraControlsClass } from 'camera-controls'
Updated 😉

2024-04-22 19:20 UTC, JaimeTorrealba approved these changes
Great work man!

2024-04-22 19:21 UTC, merged