feat(Fit): add component, playground, demo
Tresjs/cientos pull request #389
Opened 2024-04-29 13:45 UTC by andretchen0

closes #379

This component is similar in spirit to Drei's `<Resize />`. But it also allows for scaling/positioning children of `<Fit />` to:

* fit in a `Box3`
* fit in an `Object3D`'s computed `AABB`
* fit into a 1 x 1 x 1 `Box3` at world origin if no `:into` prop is provided

2024-04-30 17:01 UTC, JaimeTorrealba requested changes
Nice one, I was playing with it, works just fine.

I just drop little changes, nothing too big

Also, please your demo is fantastic, but some comments would improve drastically the component, I was struggling understanding what's going on hahaha

2024-04-30 19:01 UTC, andretchen0 commented
> Nice one, I was playing with it, works just fine.
> 
> I just drop little changes, nothing too big
> 
> Also, please your demo is fantastic, but some comments would improve drastically the component, I was struggling understanding what's going on hahaha

Hey! Thanks for the feedback. Always nice to get fresh eyes on something.

2024-04-30 19:56 UTC, andretchen0 commented on src/core/staging/Fit.vue
> +  setTimeout(() => fit(props.into, props.precise), 5)
Good catch. Updated to use `nextTick`.

2024-04-30 19:58 UTC, andretchen0 commented on playground/src/pages/staging/FitDemo.vue
> +import RandUtils from '../../../../src/core/abstractions/Lensflare/RandUtils'
I think last time we discussed it – six months ago? – we decided not to put it in `utils`. I'm open to whatever though.

2024-04-30 20:06 UTC, andretchen0 commented on src/core/staging/Fit.vue
> +    // NOTE: Nothing to do.
> not doing anything

There are 2 cases here:

* No children, so there's nothing to 'fit'. We can return early for an efficiency gain.
* `:into` has been explicitly set to `null` by the user, which is the way to signal to the component that it shouldn't scale/position the children. That's documented and shouldn't be a surprise.

In the first case, I guess it could be user error – they didn't put any children in the component. But if we log, it'll also log for e.g.:

```
<Fit>
<TresMesh v-if="currentlyFalseButTrueLater">...</TresMesh>
</Fit>
```

I don't think we want to log there.

In the second case, the user has explicitly set the value to `null`. Setting to `null` is the way to signal to the system that the `<Fit />` transforms should be reset. So it's not doing nothing. It's just turning off.

I don't think we want to log there either, because it's (hopefully) doing what the user asked.

2024-04-30 20:13 UTC, andretchen0 commented on src/core/staging/Fit.vue
> +    if (container.length < 1) container.push(1)
I see what you mean. To simplify the code, I changed the prop type from `number[]` to `[number, number, number]`.

2024-04-30 20:20 UTC, andretchen0 commented
> Also, please your demo is fantastic, but some comments would improve drastically the component, I was struggling understanding what's going on hahaha

No problem. Would you like the demo to be commented, or the component, or both? Any parts in particular?

2024-05-01 08:45 UTC, JaimeTorrealba commented on playground/src/pages/staging/FitDemo.vue
> +import RandUtils from '../../../../src/core/abstractions/Lensflare/RandUtils'
Really I don't remember haha. Is not blocking so NP

2024-05-01 08:46 UTC, JaimeTorrealba commented
> > Also, please your demo is fantastic, but some comments would improve drastically the component, I was struggling understanding what's going on hahaha
> 
> @JaimeTorrealba No problem. Would you like the demo to be commented, or the component, or both? Any parts in particular?
> 
> I added some comments in the component and the playground demo. Let me know if there's another place you feel would be helpful.

This is more for future features :)

2024-05-01 09:28 UTC, JaimeTorrealba commented
@andretchen0 Hi man sorry for write here again, we're going to release the 3.9 of cientos because we have several features. I would like to include this, are you ok if I solve the conflicts? or you prefer solve them ??

2024-05-01 18:01 UTC, andretchen0 commented
Hey @JaimeTorrealba , I fixed the conflict by merging in the latest `main`. 

But latest `main` broke the linter. I can't lint and so can't pass the CI linter.

2024-05-02 13:35 UTC, merged