feat: edges
Tresjs/cientos pull request #390
Opened 2024-04-29 20:17 UTC by damienmontastier

## Edges

[Local Playground](http://localhost:5173/abstractions/edges) — `pnpm run playground`

[Local Documentation](http://localhost:5173/guide/abstractions/edges) — `pnpm run docs:dev`
___

### Description
Component based on the Three.js [EdgesGeometry](https://threejs.org/docs/#api/en/geometries/EdgesGeometry) class.

- Easy to set up as it automatically derives geometry from its parent
- You can simply wrap it around any [Object3D](https://threejs.org/docs/#api/en/core/Object3D), [Mesh](https://threejs.org/docs/#api/en/objects/Mesh), or [primitive](https://docs.tresjs.org/advanced/primitive.html) to automatically apply edge rendering.
- You can give to `<Edges>` a custom material

2024-04-30 15:10 UTC, JaimeTorrealba requested changes
Hi man, I'm glad you're back :), and thanks for this one

Did you know you can now open PRs directly to TresJs (you should be now part of the team)
Regarding the PR I didn't see any major changes, just little details, as always let me know

2024-04-30 15:10 UTC, JaimeTorrealba commented on docs/guide/abstractions/edges.md
> +| **threshold**        | `number` — An edge is only rendered if the angle (in degrees) between the face normals of the adjoining faces exceeds this value  | `1`                   |
Here I would add one more column with the LineSegments as a general (properly indicated in the description) or all the linesSegment props individually (better to be explicit, trust me we target several non-advance users)

2024-04-30 15:10 UTC, JaimeTorrealba commented on docs/guide/abstractions/edges.md
> +| **threshold**        | `number` — An edge is only rendered if the angle (in degrees) between the face normals of the adjoining faces exceeds this value  | `1`                   |
Just for knowledge which props support LineSegments? I couldn't find any :o 
The ThreeJs Docs sends me to Line (but this doesn't have any specific props, I was spectic line width or line-width but couldn't find any)

2024-11-27 10:41 UTC, andretchen0 commented
Hey @damienmontastier ,

Are you still working on this?

2024-11-27 12:43 UTC, damienmontastier commented
Hey @andretchen0 ! 
I can continue on it, like the `<Decal>`

2024-11-28 21:51 UTC, damienmontastier commented
hey @andretchen0 ! I just put a last modified version! ✌️

Previously @JaimeTorrealba had given me feedback regarding documentation [here](https://github.com/Tresjs/cientos/pull/390#discussion_r1584985347) . I think there would be the possibility of improving `<Edges>` with Line2 or something! But currently the [Line2](https://cientos.tresjs.org/guide/shapes/line2.html) instance that is returned by a defineExpose returns a null value. Maybe in the future we could have a `<Edges2>` ?

Also, on the demo, I commented some code, there's currently a bug with events pointer https://github.com/Tresjs/tres/issues/801, so the code isn't functional at the moment.

2024-11-28 22:34 UTC, andretchen0 commented
> hey @andretchen0 ! I just put a last modified version! ✌️

Great!
 
> But currently the [Line2](https://cientos.tresjs.org/guide/shapes/line2.html) instance that is returned by a defineExpose returns a null value. Maybe in the future we could have a `<Edges2>` ?

There's at least one open PR for `<Line2>`. I will check this out and get back to you.

> Also, on the demo, I commented some code [here](https://github.com/Tresjs/cientos/blob/bad825a4efae3fd3ba8baa0716cd945a631d6640/docs/.vitepress/theme/components/EdgesDemo.vue#L25), there's currently a bug with events pointer [Tresjs/tres#801](https://github.com/Tresjs/tres/issues/801), so the code isn't functional at the moment.

We'll have to check that in the future, but it's not up to `<Edges>` to work around it, so don't worry about it here.

The events issue should be [fixed with this PR.](https://github.com/Tresjs/tres/pull/844) I'm not sure when it'll be merged though; it's part of a longer term project to bring portals to Tres core and I'm currently on the road and just working on smaller projects.

2024-11-28 23:05 UTC, andretchen0 commented
> But currently the [Line2](https://cientos.tresjs.org/guide/shapes/line2.html) instance that is returned by a defineExpose returns a null value.

The `defineExpose` issue will be fixed when this PR is merged: https://github.com/Tresjs/cientos/pull/523 . If you want to test on your branch, in `src\core\shapes\Line2.vue`, you just need to change `:ref` to `ref` here:

```
<template>
  <primitive
    :ref="lineRef"
    :object="line"
  />
</template>
```

2024-11-28 23:42 UTC, damienmontastier commented
Thanks @andretchen0  for your feedback! 

I'm going to modify Line2 locally tomorrow! And I'll let you know! 

Is this PR good for you? And so there will be an `<Edges2>` ?

2024-11-29 00:27 UTC, andretchen0 requested changes
Looks good! Just a few comments. 

Excited to have this one!

2024-11-29 00:27 UTC, andretchen0 commented on src/core/abstractions/Edges.vue
> +  root: lineSegmentsRef,
In Cientos' components, we're trying to stick with a convention to expose the top-level ref as `instance`, so:

```ts
defineExpose({
  instance: lineSegmentsRef,
})
```

2024-11-29 00:27 UTC, andretchen0 commented on docs/guide/abstractions/edges.md
> +The `<Edges>` component is easy to set up as it automatically derives geometry from its parent. You can simply wrap it around any [Object3D](https://threejs.org/docs/#api/en/core/Object3D), [Mesh](ht
Just a small language issue here. Change ...

> You can give to `<Edges>` a custom material. *(see code bellow)*

... to ...

> You can provide a custom material to `<Edges>`. *(see code bellow)*

2024-11-29 00:27 UTC, andretchen0 commented on playground/vue/src/pages/abstractions/EdgesDemo.vue
> +      <Edges
Not absolutely necessary, but would you mind adding a `v-if` here and a checkbox toggle in `useControls`?

That'll be helpful when testing the component as the codebase evolves.

2024-11-29 00:42 UTC, andretchen0 commented
> Is this PR good for you? 

It looks good! Docs demo is on-brand, too! I made a few review comments. Nothing major.

> And so there will be an `<Edges2>` ?

If you want to implement one and there's an advantage over the PR here, I don't think anyone would say no. Though my personal preference at the moment would be to make one, good `<Edge />` component for users.

Just FYI though, if you were comparing to Drei, their `<Line />` and our `<Line2 />` both use `THREE.Line2`. [Drei use of `THREE.Line2` here.](https://github.com/pmndrs/drei/blob/0534eb89d516ba1af01edf9fe5047465e7eae0f6/src/core/Line.tsx#L30C1-L30C96)

I called the Cientos' version `<Line2 />` since it wraps `THREE.Line2`. And to avoid conflict in case we ever wanted to have a Cientos component based on `THREE.Line`.

Since THREE doesn't have `Edges`, I'm fine with calling your component here `<Edges />`, even if you want to use `<Line2 />` or `THREE.Line2` under the hood.

Maybe @alvarosabu wants to weigh in here.

2024-11-29 06:03 UTC, andretchen0 commented on docs/.vitepress/theme/components/EdgesDemo.vue
> +<script setup lang="ts">
(non-blocking)

This is a really lovely demo.

If possible, can it be stripped down while retaining the essential functionality and then also shown as source code under "Usage"?

In Vitepress markdown, you can include the demo as source code as follows:

```md
## Usage

<<< @/.vitepress/theme/components/EdgesDemo.vue
```

### Reasoning

With Cientos (though not yet with Tres core) I've been trying to transition to showing the actual demo source code under the demos. There's still work to do, but we're getting there!

The big advantage to us is that if the demo matches the "Usage" source code, we have a chance to catch and fix a bug in the displayed source code, because the demo will often exhibit the bug, 

OTOH, we don't have the resources to test the "Usage" source, so where it isn't actually executed, it tends to accumulate bugs. We almost never find those bugs unless we're rewriting the docs or a user files an issue.

2024-11-29 08:50 UTC, damienmontastier commented on docs/guide/abstractions/edges.md
> +The `<Edges>` component is easy to set up as it automatically derives geometry from its parent. You can simply wrap it around any [Object3D](https://threejs.org/docs/#api/en/core/Object3D), [Mesh](ht
available at the next commit

2024-11-29 08:58 UTC, damienmontastier commented on playground/vue/src/pages/abstractions/EdgesDemo.vue
> +      <Edges
available at the next commit

2024-11-29 09:09 UTC, damienmontastier commented
> If you want to implement one and there's an advantage over the PR here, I don't think anyone would say no. Though my personal preference at the moment would be to make one, good `<Edge />` component for users.

Ok that's understandable! 

I'm talking about a case where the user didn't want to use **LineSegments** (for which line-width doesn't exist, it's a fixed size). Instead, he wanted to use **Line2**, which embeds line-width modification. That's why I was talking about `<Edges2 />`.

2024-11-29 09:22 UTC, damienmontastier commented
Hey @andretchen0 !

I've just pushed the last modifications you asked for in the review.

2024-11-29 21:33 UTC, andretchen0 commented
> Hey @andretchen0 !
> 
> I've just pushed the last modifications you asked for in the review.

Looks good!

2024-11-29 21:37 UTC, andretchen0 commented
> > If you want to implement one and there's an advantage over the PR here, I don't think anyone would say no. Though my personal preference at the moment would be to make one, good `<Edge />` component for users.
> 
> Ok that's understandable!
> 
> I'm talking about a case where the user didn't want to use **LineSegments** (for which line-width doesn't exist, it's a fixed size). Instead, he wanted to use **Line2**, which embeds line-width modification. That's why I was talking about `<Edges2 />`.

Ah, gotcha.

Line width would be a useful addition, so if it wouldn't be too much work to use `Line2` instead of `LineSegments` here, that'd be nice.

But I won't block the PR either way. It's good for me. Approved.

2024-11-29 21:38 UTC, andretchen0 approved these changes

2024-11-30 10:31 UTC, damienmontastier commented
Hey @andretchen0 !

Yes, I think it will be simpler to create a `<Edges2 />` for the use of Line2 and line-widths. This will avoid making `<Edges>` more complex.

Perfect! Can't wait for the next release!

2024-12-04 06:40 UTC, alvarosabu approved these changes

2024-12-04 06:47 UTC, merged