feat(app): Add the option for x and y in mouseparallax component
Tresjs/cientos pull request #444
Opened 2024-07-10 14:45 UTC by JaimeTorrealba

Small PR for improving the mouse-parallax component

v4 branch is selected

2024-07-11 16:36 UTC, andretchen0 requested changes
Hey @JaimeTorrealba . Welcome back! This is a useful change!

2024-07-11 16:36 UTC, andretchen0 commented on docs/guide/abstractions/mouse-parallax.md
> +`factor` is a number to increase the movement range of the camera. This could be an array of two values corresponding to the x and y values, in that order, ej. `:factor=[x,y]` .
Wording: 

I'm guessing "ej." is for "ejemplo", right?

I think here we'd write, "in other words" or "that is to say" or "i.e.". Or maybe just leave it out altogether:

```
This could be an array of two values corresponding to the x and y values, in that order: `:factor=[x,y]`.
```

2024-07-11 16:36 UTC, andretchen0 commented on docs/guide/abstractions/mouse-parallax.md
> +`ease` is a number that smooths the movement. This could be an array of two values corresponding to the x and y values, in that order, ej. `:ease=[x,y]` .
Wording:

Same as above. Maybe omit the "ej.":

```
This could be an array of two values corresponding to the x and y values, in that order: `:ease=[x,y]`.
```

2024-07-11 16:36 UTC, andretchen0 commented on playground/src/pages/abstractions/MouseParallaxDemo.vue
> +  <!-- <TresCanvas v-bind="gl">
We sometimes have issues in Tres caused by comments.

Since handling comments isn't what this playground is showing, can we remove this comment?

2024-07-11 16:36 UTC, andretchen0 commented on src/core/abstractions/MouseParallax.vue
> +  factor?: number | [number, number]
The JSDoc type `@type {number}` doesn't agree with the TS type `number | [number, number]`.

VS Code displays both types, so I think we should just remove the JSDoc type to make future updates easier.

2024-07-11 16:36 UTC, andretchen0 commented on src/core/abstractions/MouseParallax.vue
> +  ease?: number | [number, number]
Same as above. 

The JSDoc type `@type {number}` doesn't agree with the TS type `number | [number, number]`.

VS Code displays both types, so I think we should just remove the JSDoc type to make future updates easier.

2024-07-11 16:36 UTC, andretchen0 commented on src/core/abstractions/MouseParallax.vue
> +const _ease = Array.isArray(ease.value) ? ease.value : [ease.value, ease.value]
It seems that the props `factor` and `ease` aren't reactive.

`_factor` and `_ease` will need a `watch` or some other way to detect prop changes. Or you could add a ternary here:

```
const cursorX = computed(() => (x.value / width.value - 0.5) * _factor[0])
```

Here's a demo showing that. This should alternate between zooming around with a value of `[10, 10]` and stopping with `0`.

```vue
<script setup lang="ts">
import { TresCanvas } from '@tresjs/core'
import { MouseParallax, TorusKnot } from '@tresjs/cientos'

const factorOrFactors = shallowRef<number | [number, number]>([10, 10])
setInterval(() => {
  factorOrFactors.value = factorOrFactors.value === 0 ? [10, 10] : 0
},
  1000
)
</script>

<template>
  <TresCanvas>
    <TresPerspectiveCamera :position="[0, 0, 7.5]" />
    <TorusKnot>
      <TresMeshNormalMaterial />
    </TorusKnot>
    <MouseParallax :factor="factorOrFactors" :ease="3" />
  </TresCanvas>
</template>
```

2024-07-11 17:50 UTC, JaimeTorrealba commented on src/core/abstractions/MouseParallax.vue
> +const _ease = Array.isArray(ease.value) ? ease.value : [ease.value, ease.value]
Good one, yes I've destroy the reactivity with my last update, thanks for this one

2024-07-11 18:00 UTC, JaimeTorrealba commented on src/core/abstractions/MouseParallax.vue
> +  factor?: number | [number, number]
Do you think we should remove? I mean JSDocs accept multiples types adding just a pipe operator.
https://jsdoc.app/tags-type

Don't see why remove it

2024-07-11 19:56 UTC, andretchen0 commented on src/core/abstractions/MouseParallax.vue
> +  factor?: number | [number, number]
Hey @JaimeTorrealba ,

Keeping it means we have 2 "sources of truth" for the type. But sure, as long as they match, then it's ok to keep both.

2024-07-12 13:35 UTC, andretchen0 approved these changes
Looks good!

I caught one thing that wasn't changed in this PR, but since we're looking at component, we might as well change it. 

I won't block the PR though.

2024-07-12 13:35 UTC, andretchen0 commented on src/core/abstractions/MouseParallax.vue
>  const cameraGroupRef = ref<Group>()
(Non-blocking)

Sorry, I missed this earlier. This should probably be a `shallowRef`.

> shallowRef() is typically used for performance optimizations of large data structures, or integration with external state management systems.

https://vuejs.org/api/reactivity-advanced.html#shallowref

Since all Tres elements have a link to `context` – which includes `Scene` and all its descendants – it probably qualifies as a "large data structure."

2024-07-17 14:19 UTC, merged