chore: remove on demand composable
Tresjs/cientos pull request #452
Opened 2024-07-22 14:00 UTC by alvarosabu

2024-07-23 14:29 UTC, andretchen0 requested changes

2024-07-23 14:29 UTC, andretchen0 commented on src/core/controls/KeyboardControls.vue
There's an `invalidateOnDemand()` on 114.

2024-07-23 14:29 UTC, andretchen0 commented on src/core/staging/Fit.vue
> +watch(props, () => invalidate())
## Problem

This `watch` makes the demo drop frames when `into` is an `Object3D`.

* `pnpm run playground`
* go to http://localhost:5173/staging/fit
* click last radio button – label starts with`Object`

The demo doesn't drop frames on my machine if the `watch` is removed.

## Problem

The component exports `fit` and `update` functions that can be called by the user. Those functions do not `invalidate()`.

## Solution

* Remove the `watch`.
* Put the `invalidate()` in `fit()`. (line 41)

2024-07-24 05:13 UTC, alvarosabu commented on src/core/controls/MapControls.vue
I agree we can do this in the scope of another PR, seems to be a problem overall in the controls

2024-07-24 11:12 UTC, andretchen0 approved these changes

2024-07-24 11:31 UTC, merged