docs(app): Improve docs examples with code group to avoid confusion
Tresjs/cientos pull request #463
Opened 2024-08-07 20:51 UTC by JaimeTorrealba

2024-08-12 09:04 UTC, alvarosabu requested changes
Great idea @JaimeTorrealba, hopefully this will educate community about async usage on cientos.

I just added minor suggestion on the naming of components. 

Thanks for the PR

2024-08-12 09:04 UTC, alvarosabu commented on docs/guide/loaders/use-fbx.md
> +import AsyncComponent from './AsyncComponent.vue'
```suggestion
import TheModel from './TheModel.vue'
```

2024-08-12 09:04 UTC, alvarosabu commented on docs/guide/loaders/use-fbx.md
> +      <AsyncComponent />
```suggestion
      <TheModel />
```

2024-08-12 09:04 UTC, alvarosabu commented on docs/guide/loaders/use-fbx.md
> +```vue{2,6} [AsyncComponent.vue]
```suggestion
```vue{2,6} [TheModel.vue]
```

2024-08-12 09:04 UTC, alvarosabu commented on docs/guide/loaders/use-gltf.md
> +import AsyncComponent from './AsyncComponent.vue'
```suggestion
import TheModel from './TheModel.vue'
```

2024-08-12 09:04 UTC, alvarosabu commented on docs/guide/loaders/use-gltf.md
> +      <AsyncComponent />
```suggestion
      <TheModel />
```

2024-08-12 09:04 UTC, alvarosabu commented on docs/guide/loaders/use-gltf.md
> +```vue{2,6} [AsyncComponent.vue]
```suggestion
```vue{2,6} [TheModel.vue]
```

2024-08-12 09:04 UTC, alvarosabu commented on docs/guide/loaders/use-video-texture.md
> +import AsyncComponent from './AsyncComponent.vue'
```suggestion
import TheVideoTexture from './TheVideoTexture.vue'
```

2024-08-12 09:04 UTC, alvarosabu commented on docs/guide/loaders/use-video-texture.md
> +      <AsyncComponent />
```suggestion
      <TheVideoTexture />
```

2024-08-12 09:04 UTC, alvarosabu commented on docs/guide/loaders/use-video-texture.md
> +```vue{3,8,13} [AsyncComponent.vue]
```suggestion
```vue{3,8,13} [TheVideoTexture.vue]
```

2024-08-24 15:38 UTC, JaimeTorrealba commented
@alvarosabu I have fixed this one, please let me know if everything good

2024-08-29 17:34 UTC, merged