feat(Helper): add component, demo, docs
Tresjs/cientos pull request #543
Opened 2024-11-28 07:46 UTC by andretchen0

Ports Drei's `<Helper />` to Cientos. Adds:

* component
* demo
* docs

2024-12-10 19:57 UTC, alvarosabu commented on src/core/controls/Helper/useHelper.ts
> +  const scene = useTres().scene
```suggestion
  const { scene } = useTres()
```

2024-12-10 19:59 UTC, alvarosabu requested changes

2024-12-10 19:59 UTC, alvarosabu commented on src/core/controls/Helper/useHelper.ts
> +      helper.value = currentHelper = new (helperConstructor as any)(toValue(object3D), ...args)
@andretchen0 any chance we can avoid using `any` assertion here?

2024-12-11 05:54 UTC, andretchen0 commented on src/core/controls/Helper/useHelper.ts
> +      helper.value = currentHelper = new (helperConstructor as any)(toValue(object3D), ...args)
No problem. I made the change.

For what it's worth, the effect of the change is purely cosmetic. The resulting type of `helper.value` is still

```ts
Ref<HelperType | undefined, HelperType | undefined>.value: HelperType | undefined
```

2024-12-11 05:55 UTC, andretchen0 commented on src/core/controls/Helper/useHelper.ts
> +  const scene = useTres().scene
Done

2024-12-13 09:42 UTC, merged