feat(MarchingCubes): add component, demo, docs
Tresjs/cientos pull request #553
Opened 2024-12-03 11:11 UTC by andretchen0

Port of THREE/Drei's `<MarchingCubes />` to Cientos. Adds:

* component
* demo
* docs

2024-12-13 14:40 UTC, JvanderHeide commented
Would love to see this merged

2024-12-13 19:47 UTC, andretchen0 commented
> Would love to see this merged

Good to hear!

2024-12-14 09:24 UTC, alvarosabu requested changes
I really like this abstraction. I just have some questions about how to use materials and some typescript stuff long the way

2024-12-14 09:24 UTC, alvarosabu commented on src/core/abstractions/MarchingCubes/MarchingCubes.vue
> +const marchingCubes = computed(() => new MarchingCubesImpl(props.resolution, null as unknown as Material, props.enableUvs, props.enableColors, props.maxPolyCount))
mmm... @andretchen0 I don't think we should pass a null and cast it as a material.

Should we use a `new MeshBasicMaterial` as default or maybe enable a prop to pass a material? How does the MarchingCubes get the material from? Like this?

```
<MarchingCubes :enable-colors="true" :resolution="40" :max-poly-count="40000">
      <MarchingPlane v-if="c.hasWallX.value.value" plane-type="x" />
      <MarchingCube
        :position="[c.x.value.value, c.y.value.value, c.z.value.value]"
        :strength="c.strength.value.value"
        :subtract="c.subtract.value.value"
      />
      <MarchingCube ref="r0" color="red" />


      <TresMeshBasicMaterial v-if="c.enableColors.value.value" :vertex-colors="true" />
      <TresMeshPhongMaterial v-else specular="#111111" :shininess="30" color="#049ef4" :reflectivity="1" />
    </MarchingCubes>
```

2024-12-14 09:29 UTC, alvarosabu commented on src/core/abstractions/MarchingCubes/MarchingCubes.vue
> +const marchingCubes = computed(() => new MarchingCubesImpl(props.resolution, null as unknown as Material, props.enableUvs, props.enableColors, props.maxPolyCount))
@andretchen0 I just answered my own question, changed the `MeshPhongMaterial` on the playground for `Toon Material` and all good. Also with the default `MeshBasicMaterial` on the constructor

2024-12-14 13:18 UTC, andretchen0 commented on src/core/abstractions/MarchingCubes/MarchingCubes.vue
> +const marchingCubes = computed(() => new MarchingCubesImpl(props.resolution, null as unknown as Material, props.enableUvs, props.enableColors, props.maxPolyCount))
Hey @alvarosabu 

> I just answered my own question

Great! Is this issue resolved?

2024-12-16 21:17 UTC, andretchen0 commented on src/core/abstractions/MarchingCubes/MarchingCubes.vue
> +const marchingCubes = computed(() => new MarchingCubesImpl(props.resolution, null as unknown as Material, props.enableUvs, props.enableColors, props.maxPolyCount))
After the follow-up on Discord, I've added a default material.

2024-12-17 08:19 UTC, alvarosabu approved these changes

2024-12-17 08:20 UTC, merged