feat(Stage): add component, demo, docs
Tresjs/cientos pull request #572
Opened 2024-12-20 23:01 UTC by andretchen0

Port of Drei's `<Stage />` to Cientos. Adds:

* component
* demo
* docs

2025-01-02 14:20 UTC, alvarosabu approved these changes

2025-01-02 14:35 UTC, alvarosabu requested changes
I'm getting quite some Typescript errors on the Stage.vue file @andretchen0 could you please take a look?

![Screenshot 2025-01-02 at 15 32 46](https://github.com/user-attachments/assets/97ba16f2-f79b-4c42-8c72-dcbc7173a68e)
![Screenshot 2025-01-02 at 15 34 30](https://github.com/user-attachments/assets/d6bfba6f-335b-4b0a-93f4-349ea4a1784a)

2025-01-02 17:00 UTC, andretchen0 commented
> I'm getting quite some Typescript errors on the Stage.vue file @andretchen0 could you please take a look?

Sure thing. Updated.

2025-01-03 14:32 UTC, alvarosabu approved these changes

2025-01-03 14:32 UTC, merged