feat: 53 rain
Tresjs/cientos pull request #71
Opened 2023-05-17 19:09 UTC by JaimeTorrealba

#close 53

2023-05-17 19:10 UTC, JaimeTorrealba commented
@alvarosabu please help with the area props (I want to use a Vector3, but I couldn't figure out how to make it works, the types)

2023-05-18 09:37 UTC, alvarosabu requested changes
Great work @JaimeTorrealba the rain feels really realistic, and the props available make it very customizable. I think is gonna be a great addition to the library.

We would need to work to make those props reactive, other than that congratulations 👏🏻

2023-05-18 09:37 UTC, alvarosabu commented on src/core/abstractions/Precipitation.vue
> +  console.log(value)
Be careful to leave `console.logs` on prod code, please remove it

2023-05-18 09:37 UTC, alvarosabu commented on src/core/abstractions/Precipitation.vue
> +        <TresBufferGeometry ref="PrecipitationGeoRef" :position="[position, 3]" :velocity="[velocityArray]"  />
Is prettier working for you? The indentation here is off

2023-05-18 09:37 UTC, alvarosabu commented on src/core/abstractions/Precipitation.vue
> +const PrecipitationGeoRef = shallowRef()
Please change to `const precipitationGeoRef`, leave the Capital for Types only

2023-05-18 09:37 UTC, alvarosabu commented on src/core/abstractions/Precipitation.vue
> +  sizeAttenuation: props.sizeAttenuation
As it is right now, it will only work once `onMounted`, so none of the props would be reactive to interaction, for example, using Tweakpane to change the parameters.

2023-05-18 09:37 UTC, alvarosabu commented on playground/src/components/PrecipitationDemo.vue
> +const precipitationRef = shallowRef<Precipitation>(null)
![Screenshot 2023-05-18 at 11 36 48](https://github.com/Tresjs/cientos/assets/4699008/4813a80e-301e-4767-b713-5d9d3a2699e3)

You have a type error here, is your lint working?

2023-05-22 18:27 UTC, alvarosabu requested changes

2023-05-22 18:27 UTC, alvarosabu commented on src/core/abstractions/Precipitation.vue
> +const props = withDefaults(defineProps<PrecipitationProps>(), {
Do you feel comfortable changing this after https://github.com/Tresjs/cientos/pull/82 is merged?

2023-05-24 06:22 UTC, alvarosabu approved these changes
@JaimeTorrealba quality work 👏🏻, reactivity works perfectly and the effect is amazing, great addition

2023-05-24 06:22 UTC, merged