feat: update core 210
Tresjs/cientos pull request #82
Opened 2023-05-22 14:46 UTC by alvarosabu

2023-05-22 19:50 UTC, JaimeTorrealba requested changes

2023-05-22 19:50 UTC, JaimeTorrealba commented on src/core/shapes/Box.vue
> +watchEffect(() => {
Please rmv this console

Why do we have wireframe just in box? And no in others shapes

2023-05-22 19:50 UTC, JaimeTorrealba commented on src/core/abstractions/Smoke.vue
>  const encoding = computed(() => state.renderer?.outputColorSpace)
I have this message in console, I don't know if it is here, or in the material assign

![image](https://github.com/Tresjs/cientos/assets/63722373/e99f7839-2233-4202-8c44-ffd9704ee95b)

2023-05-22 19:50 UTC, JaimeTorrealba commented on src/core/abstractions/Smoke.vue
> +} = defineProps<SmokeProps>()
This is fantastic, definitely this way to destructure props it will be great DX.

Can you create an issue, to chg to this destructure way all the components

2023-05-23 07:47 UTC, alvarosabu commented on src/core/abstractions/Smoke.vue
> +} = defineProps<SmokeProps>()
Done https://github.com/Tresjs/cientos/issues/83

2023-05-23 07:52 UTC, alvarosabu commented on src/core/shapes/Box.vue
> +watchEffect(() => {
Testing leftover

2023-05-23 12:46 UTC, merged